#include <stdbool.h>
#include <stdlib.h>

#include "sram.h"
#include "io.h"
#include "ihex.h"
#include "emulator.h"
#include "spu-2.h"

uint16_t code[] = 
{
	// push '\r'
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ARG, INPUT_ZERO, 0, OUTPUT_PUSH, CMD_COPY),
	'\r',
	
	// push '\n'
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ARG, INPUT_ZERO, 0, OUTPUT_PUSH, CMD_COPY),
	'\n',
	
	// push '\!'
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ARG, INPUT_ZERO, 0, OUTPUT_PUSH, CMD_COPY),
	'!',
	
	// push '\o'
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ARG, INPUT_ZERO, 0, OUTPUT_PUSH, CMD_COPY),
	'o',
	
	// push '\l'
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ARG, INPUT_ZERO, 0, OUTPUT_PUSH, CMD_COPY),
	'l',
	
	// dup
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_PEEK, INPUT_ZERO, 0, OUTPUT_PUSH, CMD_COPY),
	
	// push 'e'
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ARG, INPUT_ZERO, 0, OUTPUT_PUSH, CMD_COPY),
	'e',
	
	// push 'H'
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ARG, INPUT_ZERO, 0, OUTPUT_PUSH, CMD_COPY),
	'H',
	
	// 8 * out 0
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ZERO, INPUT_POP, 0, OUTPUT_DISCARD, CMD_OUTPUT),
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ZERO, INPUT_POP, 0, OUTPUT_DISCARD, CMD_OUTPUT),
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ZERO, INPUT_POP, 0, OUTPUT_DISCARD, CMD_OUTPUT),
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ZERO, INPUT_POP, 0, OUTPUT_DISCARD, CMD_OUTPUT),
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ZERO, INPUT_POP, 0, OUTPUT_DISCARD, CMD_OUTPUT),
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ZERO, INPUT_POP, 0, OUTPUT_DISCARD, CMD_OUTPUT),
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ZERO, INPUT_POP, 0, OUTPUT_DISCARD, CMD_OUTPUT),
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ZERO, INPUT_POP, 0, OUTPUT_DISCARD, CMD_OUTPUT),
	
	// in 0
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ZERO, INPUT_ZERO, 0, OUTPUT_PUSH, CMD_INPUT),
	// out 0
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ZERO, INPUT_POP, 0, OUTPUT_DISCARD, CMD_OUTPUT),
	
	// jmp *-8
	INSTR_ENCODE(EXEC_ALWAYS, INPUT_ARG, INPUT_ZERO, 0, OUTPUT_RJUMP, CMD_COPY),
	-8
};

#include <stdio.h>

int main()
{
	mem_init();
	emu_init();
	io_init();
	
	// Initialize memory :)
	/*const unsigned count = (sizeof(code) / sizeof(code[0]));*/
	/*for(unsigned i = 0; i < count; i++) {*/
		/*mem_write16(2*i, code[i]);*/
	/*}*/
	
	ihex_load();
	
	while(true)
	{
		emu_step();
	}
	
	return 0;
}