

local device_map = 
{
  {
    name  = "MMU",
    reg16 = 18,
    url = "mmu.md",
  },
  {
    name  = "IRQ",
    reg16 = 6,
    url = "irq.md",
  },
  {
    name  = "UART 16C550-Style",
    count = 4,
    reg8  = 8,
    url = "uart.md",
  },
  {
    name  = "PS/2",
    count = 2,
    reg16 = 2,
    url = "ps2.md",
  },
  {
    name  = "IDE / PATA",
    reg16 = 8,
    url = "ide.md",
  },
  {
    name  = "Timer",
    count = 2,
    reg16 = 4,
    url = "timer.md",
  },
  {
    name  = "RTC",
    reg8  = 8,
    reg16 = 3,
    url = "rtc.md",
  },
  {
    name  = "Joystick",
    count = 2,
    reg8  = 1,
    url = "joystick.md",
  },
  {
    name  = "Parallel Port",
    reg8  = 3,
    url = "parport.md",
  },
  {
    name = "PCM Audio Control/Status",
    url = "pcm.md",
  },
  {
    name = "DMA Control/Status",
    url = "dma.md",
  },
  {
    name = "VGA Card",
    reg16 = 3,
    reg8  = 2,
    url = "vga.md",
  },
  {
    name = "Ethernet",
    reg8 = 7,
    reg16 = 3,
    url = "eth.md",
  },
  {
    name = "VGA Palette Memory",
    reg16 = 256,
    align = 512,
    url = "vga.md",
  },
}

for i,v in ipairs(device_map) do
  v.count = v.count or 1
  v.reg8  = v.reg8 or 0
  v.reg16 = v.reg16 or 0
  assert(v.name)
end

local page_start = 0x7FE000
local off = 0
local align = 16

local devices = {}

for i,v in ipairs(device_map) do
  for n=1,v.count do
    -- align forward
    local a = v.align or align
    off = a * math.ceil(off / a)

    local dev = {
      offset = off,
      name = v.name,
      proto = v,
    }
    if v.count > 1 then
      dev.index = n
      dev.name = dev.name .. (" (%d)"):format(n)
    end
    devices[#devices+1] = dev

    off = off + 2 * v.reg16
    off = off + v.reg8
  end
end

io.write("<!-- autogenerated by mapper.lua -->\n")

io.write("# Register Space\n\n")

io.write("## Device Overview\n\n")

for i,v in ipairs(device_map) do
  io.write("**[", v.name, "](",v.url, "):**\n\n")

  if v.count > 1 then
    io.write(("- %d Devices\n"):format(v.count))
  else
    io.write("- 1 Device\n")
  end

  if v.reg16 > 0 then
    io.write(("- %d Registers @ 16 Bit\n"):format(v.reg16))
  end
  if v.reg8 > 0 then
    io.write(("- %d Registers @ 8 Bit\n"):format(v.reg8))
  end

  io.write("\n")
end

io.write("## Device Mapping\n\n")

-- io.write(("- Page Offset (Physical): `0x%06X`\n\n"):format(page_start))

io.write("| Address    | Offset | Peripherial                         |\n")
io.write("|------------|--------|-------------------------------------|\n")

for i,v in ipairs(devices) do
  io.write(("| `0x%06X` | %6d | %-35s |\n"):format(page_start+v.offset,v.offset,("[%s](%s)"):format( v.name,v.proto.url)))
end

io.write(("| `0x%06X` | %6d | %-35s |\n"):format(page_start+off,off,"*end of peripherials*"))