-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.2.446.3
-- Module  Version: 1.2
-- Sat Apr 25 13:30:31 2020

-- parameterized module component declaration
component embedded_function_block
    port (wb_clk_i: in  std_logic; wb_rst_i: in  std_logic; 
        wb_cyc_i: in  std_logic; wb_stb_i: in  std_logic; 
        wb_we_i: in  std_logic; 
        wb_adr_i: in  std_logic_vector(7 downto 0); 
        wb_dat_i: in  std_logic_vector(7 downto 0); 
        wb_dat_o: out  std_logic_vector(7 downto 0); 
        wb_ack_o: out  std_logic; wbc_ufm_irq: out  std_logic);
end component;

-- parameterized module component instance
__ : embedded_function_block
    port map (wb_clk_i=>__, wb_rst_i=>__, wb_cyc_i=>__, wb_stb_i=>__, 
        wb_we_i=>__, wb_adr_i(7 downto 0)=>__, wb_dat_i(7 downto 0)=>__, 
        wb_dat_o(7 downto 0)=>__, wb_ack_o=>__, wbc_ufm_irq=>__);
