-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.11.2.446.3
-- Module  Version: 4.9
--/usr/local/diamond/3.11_x64/ispfpga/bin/lin64/scuba -w -n hw_mult_16 -lang vhdl -synth lse -bus_exp 7 -bb -arch xo3c00f -type dspmult -simple_portname -pfu_mult -widtha 16 -widthb 16 -widthp 32 -signed -PL_stages 0 -input_reg -output_reg -clk0 -ce0 -rst0 

-- Sat Apr 25 12:46:37 2020

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO3L;
use MACHXO3L.components.all;
-- synopsys translate_on

entity hw_mult_16 is
    port (
        Clock: in  std_logic; 
        ClkEn: in  std_logic; 
        Aclr: in  std_logic; 
        DataA: in  std_logic_vector(15 downto 0); 
        DataB: in  std_logic_vector(15 downto 0); 
        Result: out  std_logic_vector(31 downto 0));
end hw_mult_16;

architecture Structure of hw_mult_16 is

    -- internal signal declarations
    signal hw_mult_16_0_pp_0_0: std_logic;
    signal rego_o_0: std_logic;
    signal rego_o_1: std_logic;
    signal rego_o_2: std_logic;
    signal rego_o_3: std_logic;
    signal rego_o_4: std_logic;
    signal rego_o_5: std_logic;
    signal rego_o_6: std_logic;
    signal rego_o_7: std_logic;
    signal s_hw_mult_16_0_0_2: std_logic;
    signal hw_mult_16_0_pp_1_2: std_logic;
    signal s_hw_mult_16_0_0_3: std_logic;
    signal co_hw_mult_16_0_0_1: std_logic;
    signal co_hw_mult_16_0_0_2: std_logic;
    signal co_hw_mult_16_0_0_3: std_logic;
    signal co_hw_mult_16_0_0_4: std_logic;
    signal co_hw_mult_16_0_0_5: std_logic;
    signal co_hw_mult_16_0_0_6: std_logic;
    signal co_hw_mult_16_0_0_7: std_logic;
    signal co_hw_mult_16_0_0_8: std_logic;
    signal hw_mult_16_0_pp_0_17: std_logic;
    signal co_hw_mult_16_0_0_9: std_logic;
    signal hw_mult_16_0_pp_1_19: std_logic;
    signal co_hw_mult_16_0_0_10: std_logic;
    signal hw_mult_16_0_pp_3_6: std_logic;
    signal co_hw_mult_16_0_1_1: std_logic;
    signal co_hw_mult_16_0_1_2: std_logic;
    signal co_hw_mult_16_0_1_3: std_logic;
    signal co_hw_mult_16_0_1_4: std_logic;
    signal co_hw_mult_16_0_1_5: std_logic;
    signal co_hw_mult_16_0_1_6: std_logic;
    signal co_hw_mult_16_0_1_7: std_logic;
    signal co_hw_mult_16_0_1_8: std_logic;
    signal hw_mult_16_0_pp_2_21: std_logic;
    signal co_hw_mult_16_0_1_9: std_logic;
    signal hw_mult_16_0_pp_3_23: std_logic;
    signal co_hw_mult_16_0_1_10: std_logic;
    signal hw_mult_16_0_pp_5_10: std_logic;
    signal co_hw_mult_16_0_2_1: std_logic;
    signal co_hw_mult_16_0_2_2: std_logic;
    signal co_hw_mult_16_0_2_3: std_logic;
    signal co_hw_mult_16_0_2_4: std_logic;
    signal co_hw_mult_16_0_2_5: std_logic;
    signal co_hw_mult_16_0_2_6: std_logic;
    signal co_hw_mult_16_0_2_7: std_logic;
    signal co_hw_mult_16_0_2_8: std_logic;
    signal hw_mult_16_0_pp_4_25: std_logic;
    signal co_hw_mult_16_0_2_9: std_logic;
    signal hw_mult_16_0_pp_5_27: std_logic;
    signal co_hw_mult_16_0_2_10: std_logic;
    signal hw_mult_16_0_pp_7_14: std_logic;
    signal co_hw_mult_16_0_3_1: std_logic;
    signal co_hw_mult_16_0_3_2: std_logic;
    signal co_hw_mult_16_0_3_3: std_logic;
    signal co_hw_mult_16_0_3_4: std_logic;
    signal co_hw_mult_16_0_3_5: std_logic;
    signal co_hw_mult_16_0_3_6: std_logic;
    signal co_hw_mult_16_0_3_7: std_logic;
    signal co_hw_mult_16_0_3_8: std_logic;
    signal hw_mult_16_0_pp_6_29: std_logic;
    signal co_hw_mult_16_0_3_10: std_logic;
    signal co_hw_mult_16_0_3_9: std_logic;
    signal hw_mult_16_0_pp_7_31: std_logic;
    signal s_hw_mult_16_0_4_4: std_logic;
    signal hw_mult_16_0_pp_2_4: std_logic;
    signal s_hw_mult_16_0_0_4: std_logic;
    signal s_hw_mult_16_0_4_5: std_logic;
    signal s_hw_mult_16_0_4_6: std_logic;
    signal co_hw_mult_16_0_4_1: std_logic;
    signal s_hw_mult_16_0_1_6: std_logic;
    signal s_hw_mult_16_0_0_5: std_logic;
    signal s_hw_mult_16_0_0_6: std_logic;
    signal s_hw_mult_16_0_4_7: std_logic;
    signal co_hw_mult_16_0_4_2: std_logic;
    signal s_hw_mult_16_0_1_7: std_logic;
    signal s_hw_mult_16_0_1_8: std_logic;
    signal s_hw_mult_16_0_0_7: std_logic;
    signal s_hw_mult_16_0_0_8: std_logic;
    signal co_hw_mult_16_0_4_3: std_logic;
    signal s_hw_mult_16_0_1_9: std_logic;
    signal s_hw_mult_16_0_1_10: std_logic;
    signal s_hw_mult_16_0_0_9: std_logic;
    signal s_hw_mult_16_0_0_10: std_logic;
    signal co_hw_mult_16_0_4_4: std_logic;
    signal s_hw_mult_16_0_1_11: std_logic;
    signal s_hw_mult_16_0_1_12: std_logic;
    signal s_hw_mult_16_0_0_11: std_logic;
    signal s_hw_mult_16_0_0_12: std_logic;
    signal co_hw_mult_16_0_4_5: std_logic;
    signal s_hw_mult_16_0_1_13: std_logic;
    signal s_hw_mult_16_0_1_14: std_logic;
    signal s_hw_mult_16_0_0_13: std_logic;
    signal s_hw_mult_16_0_0_14: std_logic;
    signal co_hw_mult_16_0_4_6: std_logic;
    signal s_hw_mult_16_0_1_15: std_logic;
    signal s_hw_mult_16_0_1_16: std_logic;
    signal s_hw_mult_16_0_0_15: std_logic;
    signal s_hw_mult_16_0_0_16: std_logic;
    signal co_hw_mult_16_0_4_7: std_logic;
    signal s_hw_mult_16_0_1_17: std_logic;
    signal s_hw_mult_16_0_1_18: std_logic;
    signal s_hw_mult_16_0_0_17: std_logic;
    signal s_hw_mult_16_0_0_18: std_logic;
    signal co_hw_mult_16_0_4_8: std_logic;
    signal s_hw_mult_16_0_1_19: std_logic;
    signal s_hw_mult_16_0_1_20: std_logic;
    signal s_hw_mult_16_0_0_19: std_logic;
    signal s_hw_mult_16_0_0_20: std_logic;
    signal co_hw_mult_16_0_4_9: std_logic;
    signal s_hw_mult_16_0_1_21: std_logic;
    signal s_hw_mult_16_0_1_22: std_logic;
    signal s_hw_mult_16_0_0_21: std_logic;
    signal co_hw_mult_16_0_4_10: std_logic;
    signal s_hw_mult_16_0_1_23: std_logic;
    signal s_hw_mult_16_0_1_24: std_logic;
    signal co_hw_mult_16_0_4_11: std_logic;
    signal s_hw_mult_16_0_1_25: std_logic;
    signal co_hw_mult_16_0_4_12: std_logic;
    signal hw_mult_16_0_pp_6_12: std_logic;
    signal s_hw_mult_16_0_2_12: std_logic;
    signal co_hw_mult_16_0_5_1: std_logic;
    signal s_hw_mult_16_0_3_14: std_logic;
    signal s_hw_mult_16_0_2_13: std_logic;
    signal s_hw_mult_16_0_2_14: std_logic;
    signal co_hw_mult_16_0_5_2: std_logic;
    signal s_hw_mult_16_0_3_15: std_logic;
    signal s_hw_mult_16_0_3_16: std_logic;
    signal s_hw_mult_16_0_2_15: std_logic;
    signal s_hw_mult_16_0_2_16: std_logic;
    signal co_hw_mult_16_0_5_3: std_logic;
    signal s_hw_mult_16_0_3_17: std_logic;
    signal s_hw_mult_16_0_3_18: std_logic;
    signal s_hw_mult_16_0_2_17: std_logic;
    signal s_hw_mult_16_0_2_18: std_logic;
    signal co_hw_mult_16_0_5_4: std_logic;
    signal s_hw_mult_16_0_3_19: std_logic;
    signal s_hw_mult_16_0_3_20: std_logic;
    signal s_hw_mult_16_0_2_19: std_logic;
    signal s_hw_mult_16_0_2_20: std_logic;
    signal co_hw_mult_16_0_5_5: std_logic;
    signal s_hw_mult_16_0_3_21: std_logic;
    signal s_hw_mult_16_0_3_22: std_logic;
    signal s_hw_mult_16_0_2_21: std_logic;
    signal s_hw_mult_16_0_2_22: std_logic;
    signal co_hw_mult_16_0_5_6: std_logic;
    signal s_hw_mult_16_0_3_23: std_logic;
    signal s_hw_mult_16_0_3_24: std_logic;
    signal s_hw_mult_16_0_2_23: std_logic;
    signal s_hw_mult_16_0_2_24: std_logic;
    signal co_hw_mult_16_0_5_7: std_logic;
    signal s_hw_mult_16_0_3_25: std_logic;
    signal s_hw_mult_16_0_3_26: std_logic;
    signal s_hw_mult_16_0_2_25: std_logic;
    signal s_hw_mult_16_0_2_26: std_logic;
    signal co_hw_mult_16_0_5_8: std_logic;
    signal s_hw_mult_16_0_3_27: std_logic;
    signal s_hw_mult_16_0_3_28: std_logic;
    signal s_hw_mult_16_0_2_27: std_logic;
    signal s_hw_mult_16_0_2_28: std_logic;
    signal co_hw_mult_16_0_5_9: std_logic;
    signal s_hw_mult_16_0_3_29: std_logic;
    signal s_hw_mult_16_0_3_30: std_logic;
    signal s_hw_mult_16_0_2_29: std_logic;
    signal co_hw_mult_16_0_5_11: std_logic;
    signal co_hw_mult_16_0_5_10: std_logic;
    signal s_hw_mult_16_0_3_31: std_logic;
    signal rego_o_8: std_logic;
    signal hw_mult_16_0_pp_4_8: std_logic;
    signal s_hw_mult_16_0_4_8: std_logic;
    signal rego_o_9: std_logic;
    signal rego_o_10: std_logic;
    signal co_t_hw_mult_16_0_6_1: std_logic;
    signal s_hw_mult_16_0_2_10: std_logic;
    signal s_hw_mult_16_0_4_9: std_logic;
    signal s_hw_mult_16_0_4_10: std_logic;
    signal rego_o_11: std_logic;
    signal rego_o_12: std_logic;
    signal co_t_hw_mult_16_0_6_2: std_logic;
    signal s_hw_mult_16_0_2_11: std_logic;
    signal s_hw_mult_16_0_5_12: std_logic;
    signal s_hw_mult_16_0_4_11: std_logic;
    signal s_hw_mult_16_0_4_12: std_logic;
    signal rego_o_13: std_logic;
    signal rego_o_14: std_logic;
    signal co_t_hw_mult_16_0_6_3: std_logic;
    signal s_hw_mult_16_0_5_13: std_logic;
    signal s_hw_mult_16_0_5_14: std_logic;
    signal s_hw_mult_16_0_4_13: std_logic;
    signal s_hw_mult_16_0_4_14: std_logic;
    signal rego_o_15: std_logic;
    signal rego_o_16: std_logic;
    signal co_t_hw_mult_16_0_6_4: std_logic;
    signal s_hw_mult_16_0_5_15: std_logic;
    signal s_hw_mult_16_0_5_16: std_logic;
    signal s_hw_mult_16_0_4_15: std_logic;
    signal s_hw_mult_16_0_4_16: std_logic;
    signal rego_o_17: std_logic;
    signal rego_o_18: std_logic;
    signal co_t_hw_mult_16_0_6_5: std_logic;
    signal s_hw_mult_16_0_5_17: std_logic;
    signal s_hw_mult_16_0_5_18: std_logic;
    signal s_hw_mult_16_0_4_17: std_logic;
    signal s_hw_mult_16_0_4_18: std_logic;
    signal rego_o_19: std_logic;
    signal rego_o_20: std_logic;
    signal co_t_hw_mult_16_0_6_6: std_logic;
    signal s_hw_mult_16_0_5_19: std_logic;
    signal s_hw_mult_16_0_5_20: std_logic;
    signal s_hw_mult_16_0_4_19: std_logic;
    signal s_hw_mult_16_0_4_20: std_logic;
    signal rego_o_21: std_logic;
    signal rego_o_22: std_logic;
    signal co_t_hw_mult_16_0_6_7: std_logic;
    signal s_hw_mult_16_0_5_21: std_logic;
    signal s_hw_mult_16_0_5_22: std_logic;
    signal s_hw_mult_16_0_4_21: std_logic;
    signal s_hw_mult_16_0_4_22: std_logic;
    signal rego_o_23: std_logic;
    signal rego_o_24: std_logic;
    signal co_t_hw_mult_16_0_6_8: std_logic;
    signal s_hw_mult_16_0_5_23: std_logic;
    signal s_hw_mult_16_0_5_24: std_logic;
    signal s_hw_mult_16_0_4_23: std_logic;
    signal s_hw_mult_16_0_4_24: std_logic;
    signal rego_o_25: std_logic;
    signal rego_o_26: std_logic;
    signal co_t_hw_mult_16_0_6_9: std_logic;
    signal s_hw_mult_16_0_5_25: std_logic;
    signal s_hw_mult_16_0_5_26: std_logic;
    signal s_hw_mult_16_0_4_25: std_logic;
    signal s_hw_mult_16_0_4_26: std_logic;
    signal rego_o_27: std_logic;
    signal rego_o_28: std_logic;
    signal co_t_hw_mult_16_0_6_10: std_logic;
    signal s_hw_mult_16_0_5_27: std_logic;
    signal s_hw_mult_16_0_5_28: std_logic;
    signal s_hw_mult_16_0_4_27: std_logic;
    signal rego_o_29: std_logic;
    signal rego_o_30: std_logic;
    signal co_t_hw_mult_16_0_6_11: std_logic;
    signal s_hw_mult_16_0_5_29: std_logic;
    signal s_hw_mult_16_0_5_30: std_logic;
    signal rego_o_31: std_logic;
    signal co_t_hw_mult_16_0_6_13: std_logic;
    signal co_t_hw_mult_16_0_6_12: std_logic;
    signal s_hw_mult_16_0_5_31: std_logic;
    signal hw_mult_16_0_pp_0_2: std_logic;
    signal hw_mult_16_0_pp_0_1: std_logic;
    signal hw_mult_16_0_cin_lr_0: std_logic;
    signal hw_mult_16_0_pp_0_4: std_logic;
    signal hw_mult_16_0_pp_0_3: std_logic;
    signal mco: std_logic;
    signal hw_mult_16_0_pp_0_6: std_logic;
    signal hw_mult_16_0_pp_0_5: std_logic;
    signal mco_1: std_logic;
    signal hw_mult_16_0_pp_0_8: std_logic;
    signal hw_mult_16_0_pp_0_7: std_logic;
    signal mco_2: std_logic;
    signal hw_mult_16_0_pp_0_10: std_logic;
    signal hw_mult_16_0_pp_0_9: std_logic;
    signal mco_3: std_logic;
    signal hw_mult_16_0_pp_0_12: std_logic;
    signal hw_mult_16_0_pp_0_11: std_logic;
    signal mco_4: std_logic;
    signal hw_mult_16_0_pp_0_14: std_logic;
    signal hw_mult_16_0_pp_0_13: std_logic;
    signal mco_5: std_logic;
    signal regb_b_0: std_logic;
    signal mfco: std_logic;
    signal hw_mult_16_0_pp_0_16: std_logic;
    signal hw_mult_16_0_pp_0_15: std_logic;
    signal mco_6: std_logic;
    signal hw_mult_16_0_mult_0_7_n1: std_logic;
    signal hw_mult_16_0_mult_0_7_n2: std_logic;
    signal regb_b_1: std_logic;
    signal hw_mult_16_0_pp_1_4: std_logic;
    signal hw_mult_16_0_pp_1_3: std_logic;
    signal hw_mult_16_0_cin_lr_2: std_logic;
    signal hw_mult_16_0_pp_1_6: std_logic;
    signal hw_mult_16_0_pp_1_5: std_logic;
    signal mco_7: std_logic;
    signal hw_mult_16_0_pp_1_8: std_logic;
    signal hw_mult_16_0_pp_1_7: std_logic;
    signal mco_8: std_logic;
    signal hw_mult_16_0_pp_1_10: std_logic;
    signal hw_mult_16_0_pp_1_9: std_logic;
    signal mco_9: std_logic;
    signal hw_mult_16_0_pp_1_12: std_logic;
    signal hw_mult_16_0_pp_1_11: std_logic;
    signal mco_10: std_logic;
    signal hw_mult_16_0_pp_1_14: std_logic;
    signal hw_mult_16_0_pp_1_13: std_logic;
    signal mco_11: std_logic;
    signal hw_mult_16_0_pp_1_16: std_logic;
    signal hw_mult_16_0_pp_1_15: std_logic;
    signal mco_12: std_logic;
    signal mfco_1: std_logic;
    signal hw_mult_16_0_pp_1_18: std_logic;
    signal hw_mult_16_0_pp_1_17: std_logic;
    signal mco_13: std_logic;
    signal regb_b_2: std_logic;
    signal hw_mult_16_0_mult_2_7_n1: std_logic;
    signal hw_mult_16_0_mult_2_7_n2: std_logic;
    signal regb_b_3: std_logic;
    signal hw_mult_16_0_pp_2_6: std_logic;
    signal hw_mult_16_0_pp_2_5: std_logic;
    signal hw_mult_16_0_cin_lr_4: std_logic;
    signal hw_mult_16_0_pp_2_8: std_logic;
    signal hw_mult_16_0_pp_2_7: std_logic;
    signal mco_14: std_logic;
    signal hw_mult_16_0_pp_2_10: std_logic;
    signal hw_mult_16_0_pp_2_9: std_logic;
    signal mco_15: std_logic;
    signal hw_mult_16_0_pp_2_12: std_logic;
    signal hw_mult_16_0_pp_2_11: std_logic;
    signal mco_16: std_logic;
    signal hw_mult_16_0_pp_2_14: std_logic;
    signal hw_mult_16_0_pp_2_13: std_logic;
    signal mco_17: std_logic;
    signal hw_mult_16_0_pp_2_16: std_logic;
    signal hw_mult_16_0_pp_2_15: std_logic;
    signal mco_18: std_logic;
    signal hw_mult_16_0_pp_2_18: std_logic;
    signal hw_mult_16_0_pp_2_17: std_logic;
    signal mco_19: std_logic;
    signal mfco_2: std_logic;
    signal hw_mult_16_0_pp_2_20: std_logic;
    signal hw_mult_16_0_pp_2_19: std_logic;
    signal mco_20: std_logic;
    signal regb_b_4: std_logic;
    signal hw_mult_16_0_mult_4_7_n1: std_logic;
    signal hw_mult_16_0_mult_4_7_n2: std_logic;
    signal regb_b_5: std_logic;
    signal hw_mult_16_0_pp_3_8: std_logic;
    signal hw_mult_16_0_pp_3_7: std_logic;
    signal hw_mult_16_0_cin_lr_6: std_logic;
    signal hw_mult_16_0_pp_3_10: std_logic;
    signal hw_mult_16_0_pp_3_9: std_logic;
    signal mco_21: std_logic;
    signal hw_mult_16_0_pp_3_12: std_logic;
    signal hw_mult_16_0_pp_3_11: std_logic;
    signal mco_22: std_logic;
    signal hw_mult_16_0_pp_3_14: std_logic;
    signal hw_mult_16_0_pp_3_13: std_logic;
    signal mco_23: std_logic;
    signal hw_mult_16_0_pp_3_16: std_logic;
    signal hw_mult_16_0_pp_3_15: std_logic;
    signal mco_24: std_logic;
    signal hw_mult_16_0_pp_3_18: std_logic;
    signal hw_mult_16_0_pp_3_17: std_logic;
    signal mco_25: std_logic;
    signal hw_mult_16_0_pp_3_20: std_logic;
    signal hw_mult_16_0_pp_3_19: std_logic;
    signal mco_26: std_logic;
    signal mfco_3: std_logic;
    signal hw_mult_16_0_pp_3_22: std_logic;
    signal hw_mult_16_0_pp_3_21: std_logic;
    signal mco_27: std_logic;
    signal regb_b_6: std_logic;
    signal hw_mult_16_0_mult_6_7_n1: std_logic;
    signal hw_mult_16_0_mult_6_7_n2: std_logic;
    signal regb_b_7: std_logic;
    signal hw_mult_16_0_pp_4_10: std_logic;
    signal hw_mult_16_0_pp_4_9: std_logic;
    signal hw_mult_16_0_cin_lr_8: std_logic;
    signal hw_mult_16_0_pp_4_12: std_logic;
    signal hw_mult_16_0_pp_4_11: std_logic;
    signal mco_28: std_logic;
    signal hw_mult_16_0_pp_4_14: std_logic;
    signal hw_mult_16_0_pp_4_13: std_logic;
    signal mco_29: std_logic;
    signal hw_mult_16_0_pp_4_16: std_logic;
    signal hw_mult_16_0_pp_4_15: std_logic;
    signal mco_30: std_logic;
    signal hw_mult_16_0_pp_4_18: std_logic;
    signal hw_mult_16_0_pp_4_17: std_logic;
    signal mco_31: std_logic;
    signal hw_mult_16_0_pp_4_20: std_logic;
    signal hw_mult_16_0_pp_4_19: std_logic;
    signal mco_32: std_logic;
    signal hw_mult_16_0_pp_4_22: std_logic;
    signal hw_mult_16_0_pp_4_21: std_logic;
    signal mco_33: std_logic;
    signal mfco_4: std_logic;
    signal hw_mult_16_0_pp_4_24: std_logic;
    signal hw_mult_16_0_pp_4_23: std_logic;
    signal mco_34: std_logic;
    signal regb_b_8: std_logic;
    signal hw_mult_16_0_mult_8_7_n1: std_logic;
    signal hw_mult_16_0_mult_8_7_n2: std_logic;
    signal regb_b_9: std_logic;
    signal hw_mult_16_0_pp_5_12: std_logic;
    signal hw_mult_16_0_pp_5_11: std_logic;
    signal hw_mult_16_0_cin_lr_10: std_logic;
    signal hw_mult_16_0_pp_5_14: std_logic;
    signal hw_mult_16_0_pp_5_13: std_logic;
    signal mco_35: std_logic;
    signal hw_mult_16_0_pp_5_16: std_logic;
    signal hw_mult_16_0_pp_5_15: std_logic;
    signal mco_36: std_logic;
    signal hw_mult_16_0_pp_5_18: std_logic;
    signal hw_mult_16_0_pp_5_17: std_logic;
    signal mco_37: std_logic;
    signal hw_mult_16_0_pp_5_20: std_logic;
    signal hw_mult_16_0_pp_5_19: std_logic;
    signal mco_38: std_logic;
    signal hw_mult_16_0_pp_5_22: std_logic;
    signal hw_mult_16_0_pp_5_21: std_logic;
    signal mco_39: std_logic;
    signal hw_mult_16_0_pp_5_24: std_logic;
    signal hw_mult_16_0_pp_5_23: std_logic;
    signal mco_40: std_logic;
    signal mfco_5: std_logic;
    signal hw_mult_16_0_pp_5_26: std_logic;
    signal hw_mult_16_0_pp_5_25: std_logic;
    signal mco_41: std_logic;
    signal regb_b_10: std_logic;
    signal hw_mult_16_0_mult_10_7_n1: std_logic;
    signal hw_mult_16_0_mult_10_7_n2: std_logic;
    signal regb_b_11: std_logic;
    signal hw_mult_16_0_pp_6_14: std_logic;
    signal hw_mult_16_0_pp_6_13: std_logic;
    signal hw_mult_16_0_cin_lr_12: std_logic;
    signal rega_a_0: std_logic;
    signal hw_mult_16_0_pp_6_16: std_logic;
    signal hw_mult_16_0_pp_6_15: std_logic;
    signal mco_42: std_logic;
    signal hw_mult_16_0_pp_6_18: std_logic;
    signal hw_mult_16_0_pp_6_17: std_logic;
    signal mco_43: std_logic;
    signal hw_mult_16_0_pp_6_20: std_logic;
    signal hw_mult_16_0_pp_6_19: std_logic;
    signal mco_44: std_logic;
    signal hw_mult_16_0_pp_6_22: std_logic;
    signal hw_mult_16_0_pp_6_21: std_logic;
    signal mco_45: std_logic;
    signal hw_mult_16_0_pp_6_24: std_logic;
    signal hw_mult_16_0_pp_6_23: std_logic;
    signal mco_46: std_logic;
    signal hw_mult_16_0_pp_6_26: std_logic;
    signal hw_mult_16_0_pp_6_25: std_logic;
    signal mco_47: std_logic;
    signal mfco_6: std_logic;
    signal hw_mult_16_0_pp_6_28: std_logic;
    signal hw_mult_16_0_pp_6_27: std_logic;
    signal mco_48: std_logic;
    signal regb_b_12: std_logic;
    signal hw_mult_16_0_mult_12_7_n1: std_logic;
    signal hw_mult_16_0_mult_12_7_n2: std_logic;
    signal regb_b_13: std_logic;
    signal hw_mult_16_0_pp_7_16: std_logic;
    signal hw_mult_16_0_pp_7_15: std_logic;
    signal hw_mult_16_0_cin_lr_14: std_logic;
    signal rega_a_2: std_logic;
    signal hw_mult_16_0_mult_14_0_n1: std_logic;
    signal rega_a_1: std_logic;
    signal hw_mult_16_0_mult_14_0_n0: std_logic;
    signal hw_mult_16_0_pp_7_18: std_logic;
    signal hw_mult_16_0_pp_7_17: std_logic;
    signal mco_49: std_logic;
    signal rega_a_4: std_logic;
    signal hw_mult_16_0_mult_14_1_n1: std_logic;
    signal rega_a_3: std_logic;
    signal hw_mult_16_0_mult_14_1_n0: std_logic;
    signal hw_mult_16_0_pp_7_20: std_logic;
    signal hw_mult_16_0_pp_7_19: std_logic;
    signal mco_50: std_logic;
    signal rega_a_6: std_logic;
    signal hw_mult_16_0_mult_14_2_n1: std_logic;
    signal rega_a_5: std_logic;
    signal hw_mult_16_0_mult_14_2_n0: std_logic;
    signal hw_mult_16_0_pp_7_22: std_logic;
    signal hw_mult_16_0_pp_7_21: std_logic;
    signal mco_51: std_logic;
    signal rega_a_8: std_logic;
    signal hw_mult_16_0_mult_14_3_n1: std_logic;
    signal rega_a_7: std_logic;
    signal hw_mult_16_0_mult_14_3_n0: std_logic;
    signal hw_mult_16_0_pp_7_24: std_logic;
    signal hw_mult_16_0_pp_7_23: std_logic;
    signal mco_52: std_logic;
    signal rega_a_10: std_logic;
    signal hw_mult_16_0_mult_14_4_n1: std_logic;
    signal rega_a_9: std_logic;
    signal hw_mult_16_0_mult_14_4_n0: std_logic;
    signal hw_mult_16_0_pp_7_26: std_logic;
    signal hw_mult_16_0_pp_7_25: std_logic;
    signal mco_53: std_logic;
    signal rega_a_12: std_logic;
    signal hw_mult_16_0_mult_14_5_n1: std_logic;
    signal rega_a_11: std_logic;
    signal hw_mult_16_0_mult_14_5_n0: std_logic;
    signal hw_mult_16_0_pp_7_28: std_logic;
    signal hw_mult_16_0_pp_7_27: std_logic;
    signal mco_54: std_logic;
    signal rega_a_14: std_logic;
    signal hw_mult_16_0_mult_14_6_n1: std_logic;
    signal rega_a_13: std_logic;
    signal hw_mult_16_0_mult_14_6_n0: std_logic;
    signal mfco_7: std_logic;
    signal hw_mult_16_0_pp_7_30: std_logic;
    signal hw_mult_16_0_pp_7_29: std_logic;
    signal mco_55: std_logic;
    signal regb_b_14: std_logic;
    signal scuba_vlo: std_logic;
    signal regb_b_15: std_logic;
    signal rega_a_15: std_logic;
    signal hw_mult_16_0_mult_14_7_n2: std_logic;
    signal scuba_vhi: std_logic;
    signal hw_mult_16_0_mult_14_7_n0: std_logic;

    -- local component declarations
    component AND2
        port (A: in  std_logic; B: in  std_logic; Z: out  std_logic);
    end component;
    component FADD2B
        port (A0: in  std_logic; A1: in  std_logic; B0: in  std_logic; 
            B1: in  std_logic; CI: in  std_logic; COUT: out  std_logic; 
            S0: out  std_logic; S1: out  std_logic);
    end component;
    component FD1P3DX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component ND2
        port (A: in  std_logic; B: in  std_logic; Z: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component MULT2
        port (A0: in  std_logic; A1: in  std_logic; A2: in  std_logic; 
            A3: in  std_logic; B0: in  std_logic; B1: in  std_logic; 
            B2: in  std_logic; B3: in  std_logic; CI: in  std_logic; 
            P0: out  std_logic; P1: out  std_logic; CO: out  std_logic);
    end component;
    attribute GSR : string; 
    attribute GSR of FF_63 : label is "ENABLED";
    attribute GSR of FF_62 : label is "ENABLED";
    attribute GSR of FF_61 : label is "ENABLED";
    attribute GSR of FF_60 : label is "ENABLED";
    attribute GSR of FF_59 : label is "ENABLED";
    attribute GSR of FF_58 : label is "ENABLED";
    attribute GSR of FF_57 : label is "ENABLED";
    attribute GSR of FF_56 : label is "ENABLED";
    attribute GSR of FF_55 : label is "ENABLED";
    attribute GSR of FF_54 : label is "ENABLED";
    attribute GSR of FF_53 : label is "ENABLED";
    attribute GSR of FF_52 : label is "ENABLED";
    attribute GSR of FF_51 : label is "ENABLED";
    attribute GSR of FF_50 : label is "ENABLED";
    attribute GSR of FF_49 : label is "ENABLED";
    attribute GSR of FF_48 : label is "ENABLED";
    attribute GSR of FF_47 : label is "ENABLED";
    attribute GSR of FF_46 : label is "ENABLED";
    attribute GSR of FF_45 : label is "ENABLED";
    attribute GSR of FF_44 : label is "ENABLED";
    attribute GSR of FF_43 : label is "ENABLED";
    attribute GSR of FF_42 : label is "ENABLED";
    attribute GSR of FF_41 : label is "ENABLED";
    attribute GSR of FF_40 : label is "ENABLED";
    attribute GSR of FF_39 : label is "ENABLED";
    attribute GSR of FF_38 : label is "ENABLED";
    attribute GSR of FF_37 : label is "ENABLED";
    attribute GSR of FF_36 : label is "ENABLED";
    attribute GSR of FF_35 : label is "ENABLED";
    attribute GSR of FF_34 : label is "ENABLED";
    attribute GSR of FF_33 : label is "ENABLED";
    attribute GSR of FF_32 : label is "ENABLED";
    attribute GSR of FF_31 : label is "ENABLED";
    attribute GSR of FF_30 : label is "ENABLED";
    attribute GSR of FF_29 : label is "ENABLED";
    attribute GSR of FF_28 : label is "ENABLED";
    attribute GSR of FF_27 : label is "ENABLED";
    attribute GSR of FF_26 : label is "ENABLED";
    attribute GSR of FF_25 : label is "ENABLED";
    attribute GSR of FF_24 : label is "ENABLED";
    attribute GSR of FF_23 : label is "ENABLED";
    attribute GSR of FF_22 : label is "ENABLED";
    attribute GSR of FF_21 : label is "ENABLED";
    attribute GSR of FF_20 : label is "ENABLED";
    attribute GSR of FF_19 : label is "ENABLED";
    attribute GSR of FF_18 : label is "ENABLED";
    attribute GSR of FF_17 : label is "ENABLED";
    attribute GSR of FF_16 : label is "ENABLED";
    attribute GSR of FF_15 : label is "ENABLED";
    attribute GSR of FF_14 : label is "ENABLED";
    attribute GSR of FF_13 : label is "ENABLED";
    attribute GSR of FF_12 : label is "ENABLED";
    attribute GSR of FF_11 : label is "ENABLED";
    attribute GSR of FF_10 : label is "ENABLED";
    attribute GSR of FF_9 : label is "ENABLED";
    attribute GSR of FF_8 : label is "ENABLED";
    attribute GSR of FF_7 : label is "ENABLED";
    attribute GSR of FF_6 : label is "ENABLED";
    attribute GSR of FF_5 : label is "ENABLED";
    attribute GSR of FF_4 : label is "ENABLED";
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    AND2_t37: AND2
        port map (A=>rega_a_0, B=>regb_b_0, Z=>hw_mult_16_0_pp_0_0);

    ND2_t36: ND2
        port map (A=>rega_a_15, B=>regb_b_0, Z=>hw_mult_16_0_mult_0_7_n2);

    ND2_t35: ND2
        port map (A=>rega_a_15, B=>regb_b_1, Z=>hw_mult_16_0_mult_0_7_n1);

    AND2_t34: AND2
        port map (A=>rega_a_0, B=>regb_b_2, Z=>hw_mult_16_0_pp_1_2);

    ND2_t33: ND2
        port map (A=>rega_a_15, B=>regb_b_2, Z=>hw_mult_16_0_mult_2_7_n2);

    ND2_t32: ND2
        port map (A=>rega_a_15, B=>regb_b_3, Z=>hw_mult_16_0_mult_2_7_n1);

    AND2_t31: AND2
        port map (A=>rega_a_0, B=>regb_b_4, Z=>hw_mult_16_0_pp_2_4);

    ND2_t30: ND2
        port map (A=>rega_a_15, B=>regb_b_4, Z=>hw_mult_16_0_mult_4_7_n2);

    ND2_t29: ND2
        port map (A=>rega_a_15, B=>regb_b_5, Z=>hw_mult_16_0_mult_4_7_n1);

    AND2_t28: AND2
        port map (A=>rega_a_0, B=>regb_b_6, Z=>hw_mult_16_0_pp_3_6);

    ND2_t27: ND2
        port map (A=>rega_a_15, B=>regb_b_6, Z=>hw_mult_16_0_mult_6_7_n2);

    ND2_t26: ND2
        port map (A=>rega_a_15, B=>regb_b_7, Z=>hw_mult_16_0_mult_6_7_n1);

    AND2_t25: AND2
        port map (A=>rega_a_0, B=>regb_b_8, Z=>hw_mult_16_0_pp_4_8);

    ND2_t24: ND2
        port map (A=>rega_a_15, B=>regb_b_8, Z=>hw_mult_16_0_mult_8_7_n2);

    ND2_t23: ND2
        port map (A=>rega_a_15, B=>regb_b_9, Z=>hw_mult_16_0_mult_8_7_n1);

    AND2_t22: AND2
        port map (A=>rega_a_0, B=>regb_b_10, Z=>hw_mult_16_0_pp_5_10);

    ND2_t21: ND2
        port map (A=>rega_a_15, B=>regb_b_10, 
            Z=>hw_mult_16_0_mult_10_7_n2);

    ND2_t20: ND2
        port map (A=>rega_a_15, B=>regb_b_11, 
            Z=>hw_mult_16_0_mult_10_7_n1);

    AND2_t19: AND2
        port map (A=>rega_a_0, B=>regb_b_12, Z=>hw_mult_16_0_pp_6_12);

    ND2_t18: ND2
        port map (A=>rega_a_15, B=>regb_b_12, 
            Z=>hw_mult_16_0_mult_12_7_n2);

    ND2_t17: ND2
        port map (A=>rega_a_15, B=>regb_b_13, 
            Z=>hw_mult_16_0_mult_12_7_n1);

    AND2_t16: AND2
        port map (A=>rega_a_0, B=>regb_b_14, Z=>hw_mult_16_0_pp_7_14);

    ND2_t15: ND2
        port map (A=>rega_a_1, B=>regb_b_15, 
            Z=>hw_mult_16_0_mult_14_0_n1);

    ND2_t14: ND2
        port map (A=>rega_a_0, B=>regb_b_15, 
            Z=>hw_mult_16_0_mult_14_0_n0);

    ND2_t13: ND2
        port map (A=>rega_a_3, B=>regb_b_15, 
            Z=>hw_mult_16_0_mult_14_1_n1);

    ND2_t12: ND2
        port map (A=>rega_a_2, B=>regb_b_15, 
            Z=>hw_mult_16_0_mult_14_1_n0);

    ND2_t11: ND2
        port map (A=>rega_a_5, B=>regb_b_15, 
            Z=>hw_mult_16_0_mult_14_2_n1);

    ND2_t10: ND2
        port map (A=>rega_a_4, B=>regb_b_15, 
            Z=>hw_mult_16_0_mult_14_2_n0);

    ND2_t9: ND2
        port map (A=>rega_a_7, B=>regb_b_15, 
            Z=>hw_mult_16_0_mult_14_3_n1);

    ND2_t8: ND2
        port map (A=>rega_a_6, B=>regb_b_15, 
            Z=>hw_mult_16_0_mult_14_3_n0);

    ND2_t7: ND2
        port map (A=>rega_a_9, B=>regb_b_15, 
            Z=>hw_mult_16_0_mult_14_4_n1);

    ND2_t6: ND2
        port map (A=>rega_a_8, B=>regb_b_15, 
            Z=>hw_mult_16_0_mult_14_4_n0);

    ND2_t5: ND2
        port map (A=>rega_a_11, B=>regb_b_15, 
            Z=>hw_mult_16_0_mult_14_5_n1);

    ND2_t4: ND2
        port map (A=>rega_a_10, B=>regb_b_15, 
            Z=>hw_mult_16_0_mult_14_5_n0);

    ND2_t3: ND2
        port map (A=>rega_a_13, B=>regb_b_15, 
            Z=>hw_mult_16_0_mult_14_6_n1);

    ND2_t2: ND2
        port map (A=>rega_a_12, B=>regb_b_15, 
            Z=>hw_mult_16_0_mult_14_6_n0);

    ND2_t1: ND2
        port map (A=>rega_a_15, B=>regb_b_14, 
            Z=>hw_mult_16_0_mult_14_7_n2);

    ND2_t0: ND2
        port map (A=>rega_a_14, B=>regb_b_15, 
            Z=>hw_mult_16_0_mult_14_7_n0);

    FF_63: FD1P3DX
        port map (D=>DataA(0), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>rega_a_0);

    FF_62: FD1P3DX
        port map (D=>DataA(1), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>rega_a_1);

    FF_61: FD1P3DX
        port map (D=>DataA(2), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>rega_a_2);

    FF_60: FD1P3DX
        port map (D=>DataA(3), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>rega_a_3);

    FF_59: FD1P3DX
        port map (D=>DataA(4), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>rega_a_4);

    FF_58: FD1P3DX
        port map (D=>DataA(5), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>rega_a_5);

    FF_57: FD1P3DX
        port map (D=>DataA(6), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>rega_a_6);

    FF_56: FD1P3DX
        port map (D=>DataA(7), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>rega_a_7);

    FF_55: FD1P3DX
        port map (D=>DataA(8), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>rega_a_8);

    FF_54: FD1P3DX
        port map (D=>DataA(9), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>rega_a_9);

    FF_53: FD1P3DX
        port map (D=>DataA(10), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>rega_a_10);

    FF_52: FD1P3DX
        port map (D=>DataA(11), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>rega_a_11);

    FF_51: FD1P3DX
        port map (D=>DataA(12), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>rega_a_12);

    FF_50: FD1P3DX
        port map (D=>DataA(13), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>rega_a_13);

    FF_49: FD1P3DX
        port map (D=>DataA(14), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>rega_a_14);

    FF_48: FD1P3DX
        port map (D=>DataA(15), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>rega_a_15);

    FF_47: FD1P3DX
        port map (D=>DataB(0), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>regb_b_0);

    FF_46: FD1P3DX
        port map (D=>DataB(1), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>regb_b_1);

    FF_45: FD1P3DX
        port map (D=>DataB(2), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>regb_b_2);

    FF_44: FD1P3DX
        port map (D=>DataB(3), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>regb_b_3);

    FF_43: FD1P3DX
        port map (D=>DataB(4), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>regb_b_4);

    FF_42: FD1P3DX
        port map (D=>DataB(5), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>regb_b_5);

    FF_41: FD1P3DX
        port map (D=>DataB(6), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>regb_b_6);

    FF_40: FD1P3DX
        port map (D=>DataB(7), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>regb_b_7);

    FF_39: FD1P3DX
        port map (D=>DataB(8), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>regb_b_8);

    FF_38: FD1P3DX
        port map (D=>DataB(9), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>regb_b_9);

    FF_37: FD1P3DX
        port map (D=>DataB(10), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>regb_b_10);

    FF_36: FD1P3DX
        port map (D=>DataB(11), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>regb_b_11);

    FF_35: FD1P3DX
        port map (D=>DataB(12), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>regb_b_12);

    FF_34: FD1P3DX
        port map (D=>DataB(13), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>regb_b_13);

    FF_33: FD1P3DX
        port map (D=>DataB(14), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>regb_b_14);

    FF_32: FD1P3DX
        port map (D=>DataB(15), SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>regb_b_15);

    FF_31: FD1P3DX
        port map (D=>rego_o_0, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(0));

    FF_30: FD1P3DX
        port map (D=>rego_o_1, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(1));

    FF_29: FD1P3DX
        port map (D=>rego_o_2, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(2));

    FF_28: FD1P3DX
        port map (D=>rego_o_3, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(3));

    FF_27: FD1P3DX
        port map (D=>rego_o_4, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(4));

    FF_26: FD1P3DX
        port map (D=>rego_o_5, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(5));

    FF_25: FD1P3DX
        port map (D=>rego_o_6, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(6));

    FF_24: FD1P3DX
        port map (D=>rego_o_7, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(7));

    FF_23: FD1P3DX
        port map (D=>rego_o_8, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(8));

    FF_22: FD1P3DX
        port map (D=>rego_o_9, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(9));

    FF_21: FD1P3DX
        port map (D=>rego_o_10, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(10));

    FF_20: FD1P3DX
        port map (D=>rego_o_11, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(11));

    FF_19: FD1P3DX
        port map (D=>rego_o_12, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(12));

    FF_18: FD1P3DX
        port map (D=>rego_o_13, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(13));

    FF_17: FD1P3DX
        port map (D=>rego_o_14, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(14));

    FF_16: FD1P3DX
        port map (D=>rego_o_15, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(15));

    FF_15: FD1P3DX
        port map (D=>rego_o_16, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(16));

    FF_14: FD1P3DX
        port map (D=>rego_o_17, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(17));

    FF_13: FD1P3DX
        port map (D=>rego_o_18, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(18));

    FF_12: FD1P3DX
        port map (D=>rego_o_19, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(19));

    FF_11: FD1P3DX
        port map (D=>rego_o_20, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(20));

    FF_10: FD1P3DX
        port map (D=>rego_o_21, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(21));

    FF_9: FD1P3DX
        port map (D=>rego_o_22, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(22));

    FF_8: FD1P3DX
        port map (D=>rego_o_23, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(23));

    FF_7: FD1P3DX
        port map (D=>rego_o_24, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(24));

    FF_6: FD1P3DX
        port map (D=>rego_o_25, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(25));

    FF_5: FD1P3DX
        port map (D=>rego_o_26, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(26));

    FF_4: FD1P3DX
        port map (D=>rego_o_27, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(27));

    FF_3: FD1P3DX
        port map (D=>rego_o_28, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(28));

    FF_2: FD1P3DX
        port map (D=>rego_o_29, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(29));

    FF_1: FD1P3DX
        port map (D=>rego_o_30, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(30));

    FF_0: FD1P3DX
        port map (D=>rego_o_31, SP=>ClkEn, CK=>Clock, CD=>Aclr, 
            Q=>Result(31));

    hw_mult_16_0_cin_lr_add_0: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>scuba_vlo, COUT=>hw_mult_16_0_cin_lr_0, 
            S0=>open, S1=>open);

    hw_mult_16_0_Cadd_0_8: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>mfco, COUT=>open, 
            S0=>hw_mult_16_0_pp_0_17, S1=>open);

    hw_mult_16_0_cin_lr_add_2: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>scuba_vlo, COUT=>hw_mult_16_0_cin_lr_2, 
            S0=>open, S1=>open);

    hw_mult_16_0_Cadd_2_8: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>mfco_1, COUT=>open, 
            S0=>hw_mult_16_0_pp_1_19, S1=>open);

    hw_mult_16_0_cin_lr_add_4: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>scuba_vlo, COUT=>hw_mult_16_0_cin_lr_4, 
            S0=>open, S1=>open);

    hw_mult_16_0_Cadd_4_8: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>mfco_2, COUT=>open, 
            S0=>hw_mult_16_0_pp_2_21, S1=>open);

    hw_mult_16_0_cin_lr_add_6: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>scuba_vlo, COUT=>hw_mult_16_0_cin_lr_6, 
            S0=>open, S1=>open);

    hw_mult_16_0_Cadd_6_8: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>mfco_3, COUT=>open, 
            S0=>hw_mult_16_0_pp_3_23, S1=>open);

    hw_mult_16_0_cin_lr_add_8: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>scuba_vlo, COUT=>hw_mult_16_0_cin_lr_8, 
            S0=>open, S1=>open);

    hw_mult_16_0_Cadd_8_8: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>mfco_4, COUT=>open, 
            S0=>hw_mult_16_0_pp_4_25, S1=>open);

    hw_mult_16_0_cin_lr_add_10: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>scuba_vlo, COUT=>hw_mult_16_0_cin_lr_10, 
            S0=>open, S1=>open);

    hw_mult_16_0_Cadd_10_8: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>mfco_5, COUT=>open, 
            S0=>hw_mult_16_0_pp_5_27, S1=>open);

    hw_mult_16_0_cin_lr_add_12: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>scuba_vlo, COUT=>hw_mult_16_0_cin_lr_12, 
            S0=>open, S1=>open);

    hw_mult_16_0_Cadd_12_8: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>mfco_6, COUT=>open, 
            S0=>hw_mult_16_0_pp_6_29, S1=>open);

    hw_mult_16_0_cin_lr_add_14: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>scuba_vlo, COUT=>hw_mult_16_0_cin_lr_14, 
            S0=>open, S1=>open);

    hw_mult_16_0_Cadd_14_8: FADD2B
        port map (A0=>scuba_vhi, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>mfco_7, COUT=>open, 
            S0=>hw_mult_16_0_pp_7_31, S1=>open);

    Cadd_hw_mult_16_0_0_1: FADD2B
        port map (A0=>scuba_vlo, A1=>hw_mult_16_0_pp_0_2, B0=>scuba_vlo, 
            B1=>hw_mult_16_0_pp_1_2, CI=>scuba_vlo, 
            COUT=>co_hw_mult_16_0_0_1, S0=>open, S1=>s_hw_mult_16_0_0_2);

    hw_mult_16_0_add_0_2: FADD2B
        port map (A0=>hw_mult_16_0_pp_0_3, A1=>hw_mult_16_0_pp_0_4, 
            B0=>hw_mult_16_0_pp_1_3, B1=>hw_mult_16_0_pp_1_4, 
            CI=>co_hw_mult_16_0_0_1, COUT=>co_hw_mult_16_0_0_2, 
            S0=>s_hw_mult_16_0_0_3, S1=>s_hw_mult_16_0_0_4);

    hw_mult_16_0_add_0_3: FADD2B
        port map (A0=>hw_mult_16_0_pp_0_5, A1=>hw_mult_16_0_pp_0_6, 
            B0=>hw_mult_16_0_pp_1_5, B1=>hw_mult_16_0_pp_1_6, 
            CI=>co_hw_mult_16_0_0_2, COUT=>co_hw_mult_16_0_0_3, 
            S0=>s_hw_mult_16_0_0_5, S1=>s_hw_mult_16_0_0_6);

    hw_mult_16_0_add_0_4: FADD2B
        port map (A0=>hw_mult_16_0_pp_0_7, A1=>hw_mult_16_0_pp_0_8, 
            B0=>hw_mult_16_0_pp_1_7, B1=>hw_mult_16_0_pp_1_8, 
            CI=>co_hw_mult_16_0_0_3, COUT=>co_hw_mult_16_0_0_4, 
            S0=>s_hw_mult_16_0_0_7, S1=>s_hw_mult_16_0_0_8);

    hw_mult_16_0_add_0_5: FADD2B
        port map (A0=>hw_mult_16_0_pp_0_9, A1=>hw_mult_16_0_pp_0_10, 
            B0=>hw_mult_16_0_pp_1_9, B1=>hw_mult_16_0_pp_1_10, 
            CI=>co_hw_mult_16_0_0_4, COUT=>co_hw_mult_16_0_0_5, 
            S0=>s_hw_mult_16_0_0_9, S1=>s_hw_mult_16_0_0_10);

    hw_mult_16_0_add_0_6: FADD2B
        port map (A0=>hw_mult_16_0_pp_0_11, A1=>hw_mult_16_0_pp_0_12, 
            B0=>hw_mult_16_0_pp_1_11, B1=>hw_mult_16_0_pp_1_12, 
            CI=>co_hw_mult_16_0_0_5, COUT=>co_hw_mult_16_0_0_6, 
            S0=>s_hw_mult_16_0_0_11, S1=>s_hw_mult_16_0_0_12);

    hw_mult_16_0_add_0_7: FADD2B
        port map (A0=>hw_mult_16_0_pp_0_13, A1=>hw_mult_16_0_pp_0_14, 
            B0=>hw_mult_16_0_pp_1_13, B1=>hw_mult_16_0_pp_1_14, 
            CI=>co_hw_mult_16_0_0_6, COUT=>co_hw_mult_16_0_0_7, 
            S0=>s_hw_mult_16_0_0_13, S1=>s_hw_mult_16_0_0_14);

    hw_mult_16_0_add_0_8: FADD2B
        port map (A0=>hw_mult_16_0_pp_0_15, A1=>hw_mult_16_0_pp_0_16, 
            B0=>hw_mult_16_0_pp_1_15, B1=>hw_mult_16_0_pp_1_16, 
            CI=>co_hw_mult_16_0_0_7, COUT=>co_hw_mult_16_0_0_8, 
            S0=>s_hw_mult_16_0_0_15, S1=>s_hw_mult_16_0_0_16);

    hw_mult_16_0_add_0_9: FADD2B
        port map (A0=>hw_mult_16_0_pp_0_17, A1=>scuba_vlo, 
            B0=>hw_mult_16_0_pp_1_17, B1=>hw_mult_16_0_pp_1_18, 
            CI=>co_hw_mult_16_0_0_8, COUT=>co_hw_mult_16_0_0_9, 
            S0=>s_hw_mult_16_0_0_17, S1=>s_hw_mult_16_0_0_18);

    hw_mult_16_0_add_0_10: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>hw_mult_16_0_pp_1_19, 
            B1=>scuba_vlo, CI=>co_hw_mult_16_0_0_9, 
            COUT=>co_hw_mult_16_0_0_10, S0=>s_hw_mult_16_0_0_19, 
            S1=>s_hw_mult_16_0_0_20);

    Cadd_hw_mult_16_0_0_11: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>co_hw_mult_16_0_0_10, COUT=>open, 
            S0=>s_hw_mult_16_0_0_21, S1=>open);

    Cadd_hw_mult_16_0_1_1: FADD2B
        port map (A0=>scuba_vlo, A1=>hw_mult_16_0_pp_2_6, B0=>scuba_vlo, 
            B1=>hw_mult_16_0_pp_3_6, CI=>scuba_vlo, 
            COUT=>co_hw_mult_16_0_1_1, S0=>open, S1=>s_hw_mult_16_0_1_6);

    hw_mult_16_0_add_1_2: FADD2B
        port map (A0=>hw_mult_16_0_pp_2_7, A1=>hw_mult_16_0_pp_2_8, 
            B0=>hw_mult_16_0_pp_3_7, B1=>hw_mult_16_0_pp_3_8, 
            CI=>co_hw_mult_16_0_1_1, COUT=>co_hw_mult_16_0_1_2, 
            S0=>s_hw_mult_16_0_1_7, S1=>s_hw_mult_16_0_1_8);

    hw_mult_16_0_add_1_3: FADD2B
        port map (A0=>hw_mult_16_0_pp_2_9, A1=>hw_mult_16_0_pp_2_10, 
            B0=>hw_mult_16_0_pp_3_9, B1=>hw_mult_16_0_pp_3_10, 
            CI=>co_hw_mult_16_0_1_2, COUT=>co_hw_mult_16_0_1_3, 
            S0=>s_hw_mult_16_0_1_9, S1=>s_hw_mult_16_0_1_10);

    hw_mult_16_0_add_1_4: FADD2B
        port map (A0=>hw_mult_16_0_pp_2_11, A1=>hw_mult_16_0_pp_2_12, 
            B0=>hw_mult_16_0_pp_3_11, B1=>hw_mult_16_0_pp_3_12, 
            CI=>co_hw_mult_16_0_1_3, COUT=>co_hw_mult_16_0_1_4, 
            S0=>s_hw_mult_16_0_1_11, S1=>s_hw_mult_16_0_1_12);

    hw_mult_16_0_add_1_5: FADD2B
        port map (A0=>hw_mult_16_0_pp_2_13, A1=>hw_mult_16_0_pp_2_14, 
            B0=>hw_mult_16_0_pp_3_13, B1=>hw_mult_16_0_pp_3_14, 
            CI=>co_hw_mult_16_0_1_4, COUT=>co_hw_mult_16_0_1_5, 
            S0=>s_hw_mult_16_0_1_13, S1=>s_hw_mult_16_0_1_14);

    hw_mult_16_0_add_1_6: FADD2B
        port map (A0=>hw_mult_16_0_pp_2_15, A1=>hw_mult_16_0_pp_2_16, 
            B0=>hw_mult_16_0_pp_3_15, B1=>hw_mult_16_0_pp_3_16, 
            CI=>co_hw_mult_16_0_1_5, COUT=>co_hw_mult_16_0_1_6, 
            S0=>s_hw_mult_16_0_1_15, S1=>s_hw_mult_16_0_1_16);

    hw_mult_16_0_add_1_7: FADD2B
        port map (A0=>hw_mult_16_0_pp_2_17, A1=>hw_mult_16_0_pp_2_18, 
            B0=>hw_mult_16_0_pp_3_17, B1=>hw_mult_16_0_pp_3_18, 
            CI=>co_hw_mult_16_0_1_6, COUT=>co_hw_mult_16_0_1_7, 
            S0=>s_hw_mult_16_0_1_17, S1=>s_hw_mult_16_0_1_18);

    hw_mult_16_0_add_1_8: FADD2B
        port map (A0=>hw_mult_16_0_pp_2_19, A1=>hw_mult_16_0_pp_2_20, 
            B0=>hw_mult_16_0_pp_3_19, B1=>hw_mult_16_0_pp_3_20, 
            CI=>co_hw_mult_16_0_1_7, COUT=>co_hw_mult_16_0_1_8, 
            S0=>s_hw_mult_16_0_1_19, S1=>s_hw_mult_16_0_1_20);

    hw_mult_16_0_add_1_9: FADD2B
        port map (A0=>hw_mult_16_0_pp_2_21, A1=>scuba_vlo, 
            B0=>hw_mult_16_0_pp_3_21, B1=>hw_mult_16_0_pp_3_22, 
            CI=>co_hw_mult_16_0_1_8, COUT=>co_hw_mult_16_0_1_9, 
            S0=>s_hw_mult_16_0_1_21, S1=>s_hw_mult_16_0_1_22);

    hw_mult_16_0_add_1_10: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>hw_mult_16_0_pp_3_23, 
            B1=>scuba_vlo, CI=>co_hw_mult_16_0_1_9, 
            COUT=>co_hw_mult_16_0_1_10, S0=>s_hw_mult_16_0_1_23, 
            S1=>s_hw_mult_16_0_1_24);

    Cadd_hw_mult_16_0_1_11: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>co_hw_mult_16_0_1_10, COUT=>open, 
            S0=>s_hw_mult_16_0_1_25, S1=>open);

    Cadd_hw_mult_16_0_2_1: FADD2B
        port map (A0=>scuba_vlo, A1=>hw_mult_16_0_pp_4_10, B0=>scuba_vlo, 
            B1=>hw_mult_16_0_pp_5_10, CI=>scuba_vlo, 
            COUT=>co_hw_mult_16_0_2_1, S0=>open, S1=>s_hw_mult_16_0_2_10);

    hw_mult_16_0_add_2_2: FADD2B
        port map (A0=>hw_mult_16_0_pp_4_11, A1=>hw_mult_16_0_pp_4_12, 
            B0=>hw_mult_16_0_pp_5_11, B1=>hw_mult_16_0_pp_5_12, 
            CI=>co_hw_mult_16_0_2_1, COUT=>co_hw_mult_16_0_2_2, 
            S0=>s_hw_mult_16_0_2_11, S1=>s_hw_mult_16_0_2_12);

    hw_mult_16_0_add_2_3: FADD2B
        port map (A0=>hw_mult_16_0_pp_4_13, A1=>hw_mult_16_0_pp_4_14, 
            B0=>hw_mult_16_0_pp_5_13, B1=>hw_mult_16_0_pp_5_14, 
            CI=>co_hw_mult_16_0_2_2, COUT=>co_hw_mult_16_0_2_3, 
            S0=>s_hw_mult_16_0_2_13, S1=>s_hw_mult_16_0_2_14);

    hw_mult_16_0_add_2_4: FADD2B
        port map (A0=>hw_mult_16_0_pp_4_15, A1=>hw_mult_16_0_pp_4_16, 
            B0=>hw_mult_16_0_pp_5_15, B1=>hw_mult_16_0_pp_5_16, 
            CI=>co_hw_mult_16_0_2_3, COUT=>co_hw_mult_16_0_2_4, 
            S0=>s_hw_mult_16_0_2_15, S1=>s_hw_mult_16_0_2_16);

    hw_mult_16_0_add_2_5: FADD2B
        port map (A0=>hw_mult_16_0_pp_4_17, A1=>hw_mult_16_0_pp_4_18, 
            B0=>hw_mult_16_0_pp_5_17, B1=>hw_mult_16_0_pp_5_18, 
            CI=>co_hw_mult_16_0_2_4, COUT=>co_hw_mult_16_0_2_5, 
            S0=>s_hw_mult_16_0_2_17, S1=>s_hw_mult_16_0_2_18);

    hw_mult_16_0_add_2_6: FADD2B
        port map (A0=>hw_mult_16_0_pp_4_19, A1=>hw_mult_16_0_pp_4_20, 
            B0=>hw_mult_16_0_pp_5_19, B1=>hw_mult_16_0_pp_5_20, 
            CI=>co_hw_mult_16_0_2_5, COUT=>co_hw_mult_16_0_2_6, 
            S0=>s_hw_mult_16_0_2_19, S1=>s_hw_mult_16_0_2_20);

    hw_mult_16_0_add_2_7: FADD2B
        port map (A0=>hw_mult_16_0_pp_4_21, A1=>hw_mult_16_0_pp_4_22, 
            B0=>hw_mult_16_0_pp_5_21, B1=>hw_mult_16_0_pp_5_22, 
            CI=>co_hw_mult_16_0_2_6, COUT=>co_hw_mult_16_0_2_7, 
            S0=>s_hw_mult_16_0_2_21, S1=>s_hw_mult_16_0_2_22);

    hw_mult_16_0_add_2_8: FADD2B
        port map (A0=>hw_mult_16_0_pp_4_23, A1=>hw_mult_16_0_pp_4_24, 
            B0=>hw_mult_16_0_pp_5_23, B1=>hw_mult_16_0_pp_5_24, 
            CI=>co_hw_mult_16_0_2_7, COUT=>co_hw_mult_16_0_2_8, 
            S0=>s_hw_mult_16_0_2_23, S1=>s_hw_mult_16_0_2_24);

    hw_mult_16_0_add_2_9: FADD2B
        port map (A0=>hw_mult_16_0_pp_4_25, A1=>scuba_vlo, 
            B0=>hw_mult_16_0_pp_5_25, B1=>hw_mult_16_0_pp_5_26, 
            CI=>co_hw_mult_16_0_2_8, COUT=>co_hw_mult_16_0_2_9, 
            S0=>s_hw_mult_16_0_2_25, S1=>s_hw_mult_16_0_2_26);

    hw_mult_16_0_add_2_10: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>hw_mult_16_0_pp_5_27, 
            B1=>scuba_vlo, CI=>co_hw_mult_16_0_2_9, 
            COUT=>co_hw_mult_16_0_2_10, S0=>s_hw_mult_16_0_2_27, 
            S1=>s_hw_mult_16_0_2_28);

    Cadd_hw_mult_16_0_2_11: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>co_hw_mult_16_0_2_10, COUT=>open, 
            S0=>s_hw_mult_16_0_2_29, S1=>open);

    Cadd_hw_mult_16_0_3_1: FADD2B
        port map (A0=>scuba_vlo, A1=>hw_mult_16_0_pp_6_14, B0=>scuba_vlo, 
            B1=>hw_mult_16_0_pp_7_14, CI=>scuba_vlo, 
            COUT=>co_hw_mult_16_0_3_1, S0=>open, S1=>s_hw_mult_16_0_3_14);

    hw_mult_16_0_add_3_2: FADD2B
        port map (A0=>hw_mult_16_0_pp_6_15, A1=>hw_mult_16_0_pp_6_16, 
            B0=>hw_mult_16_0_pp_7_15, B1=>hw_mult_16_0_pp_7_16, 
            CI=>co_hw_mult_16_0_3_1, COUT=>co_hw_mult_16_0_3_2, 
            S0=>s_hw_mult_16_0_3_15, S1=>s_hw_mult_16_0_3_16);

    hw_mult_16_0_add_3_3: FADD2B
        port map (A0=>hw_mult_16_0_pp_6_17, A1=>hw_mult_16_0_pp_6_18, 
            B0=>hw_mult_16_0_pp_7_17, B1=>hw_mult_16_0_pp_7_18, 
            CI=>co_hw_mult_16_0_3_2, COUT=>co_hw_mult_16_0_3_3, 
            S0=>s_hw_mult_16_0_3_17, S1=>s_hw_mult_16_0_3_18);

    hw_mult_16_0_add_3_4: FADD2B
        port map (A0=>hw_mult_16_0_pp_6_19, A1=>hw_mult_16_0_pp_6_20, 
            B0=>hw_mult_16_0_pp_7_19, B1=>hw_mult_16_0_pp_7_20, 
            CI=>co_hw_mult_16_0_3_3, COUT=>co_hw_mult_16_0_3_4, 
            S0=>s_hw_mult_16_0_3_19, S1=>s_hw_mult_16_0_3_20);

    hw_mult_16_0_add_3_5: FADD2B
        port map (A0=>hw_mult_16_0_pp_6_21, A1=>hw_mult_16_0_pp_6_22, 
            B0=>hw_mult_16_0_pp_7_21, B1=>hw_mult_16_0_pp_7_22, 
            CI=>co_hw_mult_16_0_3_4, COUT=>co_hw_mult_16_0_3_5, 
            S0=>s_hw_mult_16_0_3_21, S1=>s_hw_mult_16_0_3_22);

    hw_mult_16_0_add_3_6: FADD2B
        port map (A0=>hw_mult_16_0_pp_6_23, A1=>hw_mult_16_0_pp_6_24, 
            B0=>hw_mult_16_0_pp_7_23, B1=>hw_mult_16_0_pp_7_24, 
            CI=>co_hw_mult_16_0_3_5, COUT=>co_hw_mult_16_0_3_6, 
            S0=>s_hw_mult_16_0_3_23, S1=>s_hw_mult_16_0_3_24);

    hw_mult_16_0_add_3_7: FADD2B
        port map (A0=>hw_mult_16_0_pp_6_25, A1=>hw_mult_16_0_pp_6_26, 
            B0=>hw_mult_16_0_pp_7_25, B1=>hw_mult_16_0_pp_7_26, 
            CI=>co_hw_mult_16_0_3_6, COUT=>co_hw_mult_16_0_3_7, 
            S0=>s_hw_mult_16_0_3_25, S1=>s_hw_mult_16_0_3_26);

    hw_mult_16_0_add_3_8: FADD2B
        port map (A0=>hw_mult_16_0_pp_6_27, A1=>hw_mult_16_0_pp_6_28, 
            B0=>hw_mult_16_0_pp_7_27, B1=>hw_mult_16_0_pp_7_28, 
            CI=>co_hw_mult_16_0_3_7, COUT=>co_hw_mult_16_0_3_8, 
            S0=>s_hw_mult_16_0_3_27, S1=>s_hw_mult_16_0_3_28);

    hw_mult_16_0_add_3_9: FADD2B
        port map (A0=>hw_mult_16_0_pp_6_29, A1=>scuba_vlo, 
            B0=>hw_mult_16_0_pp_7_29, B1=>hw_mult_16_0_pp_7_30, 
            CI=>co_hw_mult_16_0_3_8, COUT=>co_hw_mult_16_0_3_9, 
            S0=>s_hw_mult_16_0_3_29, S1=>s_hw_mult_16_0_3_30);

    hw_mult_16_0_add_3_10: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>hw_mult_16_0_pp_7_31, 
            B1=>scuba_vlo, CI=>co_hw_mult_16_0_3_9, 
            COUT=>co_hw_mult_16_0_3_10, S0=>s_hw_mult_16_0_3_31, 
            S1=>open);

    Cadd_hw_mult_16_0_4_1: FADD2B
        port map (A0=>scuba_vlo, A1=>s_hw_mult_16_0_0_4, B0=>scuba_vlo, 
            B1=>hw_mult_16_0_pp_2_4, CI=>scuba_vlo, 
            COUT=>co_hw_mult_16_0_4_1, S0=>open, S1=>s_hw_mult_16_0_4_4);

    hw_mult_16_0_add_4_2: FADD2B
        port map (A0=>s_hw_mult_16_0_0_5, A1=>s_hw_mult_16_0_0_6, 
            B0=>hw_mult_16_0_pp_2_5, B1=>s_hw_mult_16_0_1_6, 
            CI=>co_hw_mult_16_0_4_1, COUT=>co_hw_mult_16_0_4_2, 
            S0=>s_hw_mult_16_0_4_5, S1=>s_hw_mult_16_0_4_6);

    hw_mult_16_0_add_4_3: FADD2B
        port map (A0=>s_hw_mult_16_0_0_7, A1=>s_hw_mult_16_0_0_8, 
            B0=>s_hw_mult_16_0_1_7, B1=>s_hw_mult_16_0_1_8, 
            CI=>co_hw_mult_16_0_4_2, COUT=>co_hw_mult_16_0_4_3, 
            S0=>s_hw_mult_16_0_4_7, S1=>s_hw_mult_16_0_4_8);

    hw_mult_16_0_add_4_4: FADD2B
        port map (A0=>s_hw_mult_16_0_0_9, A1=>s_hw_mult_16_0_0_10, 
            B0=>s_hw_mult_16_0_1_9, B1=>s_hw_mult_16_0_1_10, 
            CI=>co_hw_mult_16_0_4_3, COUT=>co_hw_mult_16_0_4_4, 
            S0=>s_hw_mult_16_0_4_9, S1=>s_hw_mult_16_0_4_10);

    hw_mult_16_0_add_4_5: FADD2B
        port map (A0=>s_hw_mult_16_0_0_11, A1=>s_hw_mult_16_0_0_12, 
            B0=>s_hw_mult_16_0_1_11, B1=>s_hw_mult_16_0_1_12, 
            CI=>co_hw_mult_16_0_4_4, COUT=>co_hw_mult_16_0_4_5, 
            S0=>s_hw_mult_16_0_4_11, S1=>s_hw_mult_16_0_4_12);

    hw_mult_16_0_add_4_6: FADD2B
        port map (A0=>s_hw_mult_16_0_0_13, A1=>s_hw_mult_16_0_0_14, 
            B0=>s_hw_mult_16_0_1_13, B1=>s_hw_mult_16_0_1_14, 
            CI=>co_hw_mult_16_0_4_5, COUT=>co_hw_mult_16_0_4_6, 
            S0=>s_hw_mult_16_0_4_13, S1=>s_hw_mult_16_0_4_14);

    hw_mult_16_0_add_4_7: FADD2B
        port map (A0=>s_hw_mult_16_0_0_15, A1=>s_hw_mult_16_0_0_16, 
            B0=>s_hw_mult_16_0_1_15, B1=>s_hw_mult_16_0_1_16, 
            CI=>co_hw_mult_16_0_4_6, COUT=>co_hw_mult_16_0_4_7, 
            S0=>s_hw_mult_16_0_4_15, S1=>s_hw_mult_16_0_4_16);

    hw_mult_16_0_add_4_8: FADD2B
        port map (A0=>s_hw_mult_16_0_0_17, A1=>s_hw_mult_16_0_0_18, 
            B0=>s_hw_mult_16_0_1_17, B1=>s_hw_mult_16_0_1_18, 
            CI=>co_hw_mult_16_0_4_7, COUT=>co_hw_mult_16_0_4_8, 
            S0=>s_hw_mult_16_0_4_17, S1=>s_hw_mult_16_0_4_18);

    hw_mult_16_0_add_4_9: FADD2B
        port map (A0=>s_hw_mult_16_0_0_19, A1=>s_hw_mult_16_0_0_20, 
            B0=>s_hw_mult_16_0_1_19, B1=>s_hw_mult_16_0_1_20, 
            CI=>co_hw_mult_16_0_4_8, COUT=>co_hw_mult_16_0_4_9, 
            S0=>s_hw_mult_16_0_4_19, S1=>s_hw_mult_16_0_4_20);

    hw_mult_16_0_add_4_10: FADD2B
        port map (A0=>s_hw_mult_16_0_0_21, A1=>scuba_vlo, 
            B0=>s_hw_mult_16_0_1_21, B1=>s_hw_mult_16_0_1_22, 
            CI=>co_hw_mult_16_0_4_9, COUT=>co_hw_mult_16_0_4_10, 
            S0=>s_hw_mult_16_0_4_21, S1=>s_hw_mult_16_0_4_22);

    hw_mult_16_0_add_4_11: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>s_hw_mult_16_0_1_23, 
            B1=>s_hw_mult_16_0_1_24, CI=>co_hw_mult_16_0_4_10, 
            COUT=>co_hw_mult_16_0_4_11, S0=>s_hw_mult_16_0_4_23, 
            S1=>s_hw_mult_16_0_4_24);

    hw_mult_16_0_add_4_12: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>s_hw_mult_16_0_1_25, 
            B1=>scuba_vlo, CI=>co_hw_mult_16_0_4_11, 
            COUT=>co_hw_mult_16_0_4_12, S0=>s_hw_mult_16_0_4_25, 
            S1=>s_hw_mult_16_0_4_26);

    Cadd_hw_mult_16_0_4_13: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>co_hw_mult_16_0_4_12, COUT=>open, 
            S0=>s_hw_mult_16_0_4_27, S1=>open);

    Cadd_hw_mult_16_0_5_1: FADD2B
        port map (A0=>scuba_vlo, A1=>s_hw_mult_16_0_2_12, B0=>scuba_vlo, 
            B1=>hw_mult_16_0_pp_6_12, CI=>scuba_vlo, 
            COUT=>co_hw_mult_16_0_5_1, S0=>open, S1=>s_hw_mult_16_0_5_12);

    hw_mult_16_0_add_5_2: FADD2B
        port map (A0=>s_hw_mult_16_0_2_13, A1=>s_hw_mult_16_0_2_14, 
            B0=>hw_mult_16_0_pp_6_13, B1=>s_hw_mult_16_0_3_14, 
            CI=>co_hw_mult_16_0_5_1, COUT=>co_hw_mult_16_0_5_2, 
            S0=>s_hw_mult_16_0_5_13, S1=>s_hw_mult_16_0_5_14);

    hw_mult_16_0_add_5_3: FADD2B
        port map (A0=>s_hw_mult_16_0_2_15, A1=>s_hw_mult_16_0_2_16, 
            B0=>s_hw_mult_16_0_3_15, B1=>s_hw_mult_16_0_3_16, 
            CI=>co_hw_mult_16_0_5_2, COUT=>co_hw_mult_16_0_5_3, 
            S0=>s_hw_mult_16_0_5_15, S1=>s_hw_mult_16_0_5_16);

    hw_mult_16_0_add_5_4: FADD2B
        port map (A0=>s_hw_mult_16_0_2_17, A1=>s_hw_mult_16_0_2_18, 
            B0=>s_hw_mult_16_0_3_17, B1=>s_hw_mult_16_0_3_18, 
            CI=>co_hw_mult_16_0_5_3, COUT=>co_hw_mult_16_0_5_4, 
            S0=>s_hw_mult_16_0_5_17, S1=>s_hw_mult_16_0_5_18);

    hw_mult_16_0_add_5_5: FADD2B
        port map (A0=>s_hw_mult_16_0_2_19, A1=>s_hw_mult_16_0_2_20, 
            B0=>s_hw_mult_16_0_3_19, B1=>s_hw_mult_16_0_3_20, 
            CI=>co_hw_mult_16_0_5_4, COUT=>co_hw_mult_16_0_5_5, 
            S0=>s_hw_mult_16_0_5_19, S1=>s_hw_mult_16_0_5_20);

    hw_mult_16_0_add_5_6: FADD2B
        port map (A0=>s_hw_mult_16_0_2_21, A1=>s_hw_mult_16_0_2_22, 
            B0=>s_hw_mult_16_0_3_21, B1=>s_hw_mult_16_0_3_22, 
            CI=>co_hw_mult_16_0_5_5, COUT=>co_hw_mult_16_0_5_6, 
            S0=>s_hw_mult_16_0_5_21, S1=>s_hw_mult_16_0_5_22);

    hw_mult_16_0_add_5_7: FADD2B
        port map (A0=>s_hw_mult_16_0_2_23, A1=>s_hw_mult_16_0_2_24, 
            B0=>s_hw_mult_16_0_3_23, B1=>s_hw_mult_16_0_3_24, 
            CI=>co_hw_mult_16_0_5_6, COUT=>co_hw_mult_16_0_5_7, 
            S0=>s_hw_mult_16_0_5_23, S1=>s_hw_mult_16_0_5_24);

    hw_mult_16_0_add_5_8: FADD2B
        port map (A0=>s_hw_mult_16_0_2_25, A1=>s_hw_mult_16_0_2_26, 
            B0=>s_hw_mult_16_0_3_25, B1=>s_hw_mult_16_0_3_26, 
            CI=>co_hw_mult_16_0_5_7, COUT=>co_hw_mult_16_0_5_8, 
            S0=>s_hw_mult_16_0_5_25, S1=>s_hw_mult_16_0_5_26);

    hw_mult_16_0_add_5_9: FADD2B
        port map (A0=>s_hw_mult_16_0_2_27, A1=>s_hw_mult_16_0_2_28, 
            B0=>s_hw_mult_16_0_3_27, B1=>s_hw_mult_16_0_3_28, 
            CI=>co_hw_mult_16_0_5_8, COUT=>co_hw_mult_16_0_5_9, 
            S0=>s_hw_mult_16_0_5_27, S1=>s_hw_mult_16_0_5_28);

    hw_mult_16_0_add_5_10: FADD2B
        port map (A0=>s_hw_mult_16_0_2_29, A1=>scuba_vlo, 
            B0=>s_hw_mult_16_0_3_29, B1=>s_hw_mult_16_0_3_30, 
            CI=>co_hw_mult_16_0_5_9, COUT=>co_hw_mult_16_0_5_10, 
            S0=>s_hw_mult_16_0_5_29, S1=>s_hw_mult_16_0_5_30);

    hw_mult_16_0_add_5_11: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>s_hw_mult_16_0_3_31, 
            B1=>scuba_vlo, CI=>co_hw_mult_16_0_5_10, 
            COUT=>co_hw_mult_16_0_5_11, S0=>s_hw_mult_16_0_5_31, 
            S1=>open);

    Cadd_t_hw_mult_16_0_6_1: FADD2B
        port map (A0=>scuba_vlo, A1=>s_hw_mult_16_0_4_8, B0=>scuba_vlo, 
            B1=>hw_mult_16_0_pp_4_8, CI=>scuba_vlo, 
            COUT=>co_t_hw_mult_16_0_6_1, S0=>open, S1=>rego_o_8);

    t_hw_mult_16_0_add_6_2: FADD2B
        port map (A0=>s_hw_mult_16_0_4_9, A1=>s_hw_mult_16_0_4_10, 
            B0=>hw_mult_16_0_pp_4_9, B1=>s_hw_mult_16_0_2_10, 
            CI=>co_t_hw_mult_16_0_6_1, COUT=>co_t_hw_mult_16_0_6_2, 
            S0=>rego_o_9, S1=>rego_o_10);

    t_hw_mult_16_0_add_6_3: FADD2B
        port map (A0=>s_hw_mult_16_0_4_11, A1=>s_hw_mult_16_0_4_12, 
            B0=>s_hw_mult_16_0_2_11, B1=>s_hw_mult_16_0_5_12, 
            CI=>co_t_hw_mult_16_0_6_2, COUT=>co_t_hw_mult_16_0_6_3, 
            S0=>rego_o_11, S1=>rego_o_12);

    t_hw_mult_16_0_add_6_4: FADD2B
        port map (A0=>s_hw_mult_16_0_4_13, A1=>s_hw_mult_16_0_4_14, 
            B0=>s_hw_mult_16_0_5_13, B1=>s_hw_mult_16_0_5_14, 
            CI=>co_t_hw_mult_16_0_6_3, COUT=>co_t_hw_mult_16_0_6_4, 
            S0=>rego_o_13, S1=>rego_o_14);

    t_hw_mult_16_0_add_6_5: FADD2B
        port map (A0=>s_hw_mult_16_0_4_15, A1=>s_hw_mult_16_0_4_16, 
            B0=>s_hw_mult_16_0_5_15, B1=>s_hw_mult_16_0_5_16, 
            CI=>co_t_hw_mult_16_0_6_4, COUT=>co_t_hw_mult_16_0_6_5, 
            S0=>rego_o_15, S1=>rego_o_16);

    t_hw_mult_16_0_add_6_6: FADD2B
        port map (A0=>s_hw_mult_16_0_4_17, A1=>s_hw_mult_16_0_4_18, 
            B0=>s_hw_mult_16_0_5_17, B1=>s_hw_mult_16_0_5_18, 
            CI=>co_t_hw_mult_16_0_6_5, COUT=>co_t_hw_mult_16_0_6_6, 
            S0=>rego_o_17, S1=>rego_o_18);

    t_hw_mult_16_0_add_6_7: FADD2B
        port map (A0=>s_hw_mult_16_0_4_19, A1=>s_hw_mult_16_0_4_20, 
            B0=>s_hw_mult_16_0_5_19, B1=>s_hw_mult_16_0_5_20, 
            CI=>co_t_hw_mult_16_0_6_6, COUT=>co_t_hw_mult_16_0_6_7, 
            S0=>rego_o_19, S1=>rego_o_20);

    t_hw_mult_16_0_add_6_8: FADD2B
        port map (A0=>s_hw_mult_16_0_4_21, A1=>s_hw_mult_16_0_4_22, 
            B0=>s_hw_mult_16_0_5_21, B1=>s_hw_mult_16_0_5_22, 
            CI=>co_t_hw_mult_16_0_6_7, COUT=>co_t_hw_mult_16_0_6_8, 
            S0=>rego_o_21, S1=>rego_o_22);

    t_hw_mult_16_0_add_6_9: FADD2B
        port map (A0=>s_hw_mult_16_0_4_23, A1=>s_hw_mult_16_0_4_24, 
            B0=>s_hw_mult_16_0_5_23, B1=>s_hw_mult_16_0_5_24, 
            CI=>co_t_hw_mult_16_0_6_8, COUT=>co_t_hw_mult_16_0_6_9, 
            S0=>rego_o_23, S1=>rego_o_24);

    t_hw_mult_16_0_add_6_10: FADD2B
        port map (A0=>s_hw_mult_16_0_4_25, A1=>s_hw_mult_16_0_4_26, 
            B0=>s_hw_mult_16_0_5_25, B1=>s_hw_mult_16_0_5_26, 
            CI=>co_t_hw_mult_16_0_6_9, COUT=>co_t_hw_mult_16_0_6_10, 
            S0=>rego_o_25, S1=>rego_o_26);

    t_hw_mult_16_0_add_6_11: FADD2B
        port map (A0=>s_hw_mult_16_0_4_27, A1=>scuba_vlo, 
            B0=>s_hw_mult_16_0_5_27, B1=>s_hw_mult_16_0_5_28, 
            CI=>co_t_hw_mult_16_0_6_10, COUT=>co_t_hw_mult_16_0_6_11, 
            S0=>rego_o_27, S1=>rego_o_28);

    t_hw_mult_16_0_add_6_12: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>s_hw_mult_16_0_5_29, 
            B1=>s_hw_mult_16_0_5_30, CI=>co_t_hw_mult_16_0_6_11, 
            COUT=>co_t_hw_mult_16_0_6_12, S0=>rego_o_29, S1=>rego_o_30);

    t_hw_mult_16_0_add_6_13: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>s_hw_mult_16_0_5_31, 
            B1=>scuba_vlo, CI=>co_t_hw_mult_16_0_6_12, 
            COUT=>co_t_hw_mult_16_0_6_13, S0=>rego_o_31, S1=>open);

    hw_mult_16_0_mult_0_0: MULT2
        port map (A0=>rega_a_0, A1=>rega_a_1, A2=>rega_a_1, A3=>rega_a_2, 
            B0=>regb_b_1, B1=>regb_b_0, B2=>regb_b_1, B3=>regb_b_0, 
            CI=>hw_mult_16_0_cin_lr_0, P0=>hw_mult_16_0_pp_0_1, 
            P1=>hw_mult_16_0_pp_0_2, CO=>mco);

    hw_mult_16_0_mult_0_1: MULT2
        port map (A0=>rega_a_2, A1=>rega_a_3, A2=>rega_a_3, A3=>rega_a_4, 
            B0=>regb_b_1, B1=>regb_b_0, B2=>regb_b_1, B3=>regb_b_0, 
            CI=>mco, P0=>hw_mult_16_0_pp_0_3, P1=>hw_mult_16_0_pp_0_4, 
            CO=>mco_1);

    hw_mult_16_0_mult_0_2: MULT2
        port map (A0=>rega_a_4, A1=>rega_a_5, A2=>rega_a_5, A3=>rega_a_6, 
            B0=>regb_b_1, B1=>regb_b_0, B2=>regb_b_1, B3=>regb_b_0, 
            CI=>mco_1, P0=>hw_mult_16_0_pp_0_5, P1=>hw_mult_16_0_pp_0_6, 
            CO=>mco_2);

    hw_mult_16_0_mult_0_3: MULT2
        port map (A0=>rega_a_6, A1=>rega_a_7, A2=>rega_a_7, A3=>rega_a_8, 
            B0=>regb_b_1, B1=>regb_b_0, B2=>regb_b_1, B3=>regb_b_0, 
            CI=>mco_2, P0=>hw_mult_16_0_pp_0_7, P1=>hw_mult_16_0_pp_0_8, 
            CO=>mco_3);

    hw_mult_16_0_mult_0_4: MULT2
        port map (A0=>rega_a_8, A1=>rega_a_9, A2=>rega_a_9, 
            A3=>rega_a_10, B0=>regb_b_1, B1=>regb_b_0, B2=>regb_b_1, 
            B3=>regb_b_0, CI=>mco_3, P0=>hw_mult_16_0_pp_0_9, 
            P1=>hw_mult_16_0_pp_0_10, CO=>mco_4);

    hw_mult_16_0_mult_0_5: MULT2
        port map (A0=>rega_a_10, A1=>rega_a_11, A2=>rega_a_11, 
            A3=>rega_a_12, B0=>regb_b_1, B1=>regb_b_0, B2=>regb_b_1, 
            B3=>regb_b_0, CI=>mco_4, P0=>hw_mult_16_0_pp_0_11, 
            P1=>hw_mult_16_0_pp_0_12, CO=>mco_5);

    hw_mult_16_0_mult_0_6: MULT2
        port map (A0=>rega_a_12, A1=>rega_a_13, A2=>rega_a_13, 
            A3=>rega_a_14, B0=>regb_b_1, B1=>regb_b_0, B2=>regb_b_1, 
            B3=>regb_b_0, CI=>mco_5, P0=>hw_mult_16_0_pp_0_13, 
            P1=>hw_mult_16_0_pp_0_14, CO=>mco_6);

    hw_mult_16_0_mult_0_7: MULT2
        port map (A0=>rega_a_14, A1=>hw_mult_16_0_mult_0_7_n2, 
            A2=>hw_mult_16_0_mult_0_7_n1, A3=>scuba_vhi, B0=>regb_b_1, 
            B1=>scuba_vhi, B2=>scuba_vhi, B3=>scuba_vhi, CI=>mco_6, 
            P0=>hw_mult_16_0_pp_0_15, P1=>hw_mult_16_0_pp_0_16, CO=>mfco);

    hw_mult_16_0_mult_2_0: MULT2
        port map (A0=>rega_a_0, A1=>rega_a_1, A2=>rega_a_1, A3=>rega_a_2, 
            B0=>regb_b_3, B1=>regb_b_2, B2=>regb_b_3, B3=>regb_b_2, 
            CI=>hw_mult_16_0_cin_lr_2, P0=>hw_mult_16_0_pp_1_3, 
            P1=>hw_mult_16_0_pp_1_4, CO=>mco_7);

    hw_mult_16_0_mult_2_1: MULT2
        port map (A0=>rega_a_2, A1=>rega_a_3, A2=>rega_a_3, A3=>rega_a_4, 
            B0=>regb_b_3, B1=>regb_b_2, B2=>regb_b_3, B3=>regb_b_2, 
            CI=>mco_7, P0=>hw_mult_16_0_pp_1_5, P1=>hw_mult_16_0_pp_1_6, 
            CO=>mco_8);

    hw_mult_16_0_mult_2_2: MULT2
        port map (A0=>rega_a_4, A1=>rega_a_5, A2=>rega_a_5, A3=>rega_a_6, 
            B0=>regb_b_3, B1=>regb_b_2, B2=>regb_b_3, B3=>regb_b_2, 
            CI=>mco_8, P0=>hw_mult_16_0_pp_1_7, P1=>hw_mult_16_0_pp_1_8, 
            CO=>mco_9);

    hw_mult_16_0_mult_2_3: MULT2
        port map (A0=>rega_a_6, A1=>rega_a_7, A2=>rega_a_7, A3=>rega_a_8, 
            B0=>regb_b_3, B1=>regb_b_2, B2=>regb_b_3, B3=>regb_b_2, 
            CI=>mco_9, P0=>hw_mult_16_0_pp_1_9, P1=>hw_mult_16_0_pp_1_10, 
            CO=>mco_10);

    hw_mult_16_0_mult_2_4: MULT2
        port map (A0=>rega_a_8, A1=>rega_a_9, A2=>rega_a_9, 
            A3=>rega_a_10, B0=>regb_b_3, B1=>regb_b_2, B2=>regb_b_3, 
            B3=>regb_b_2, CI=>mco_10, P0=>hw_mult_16_0_pp_1_11, 
            P1=>hw_mult_16_0_pp_1_12, CO=>mco_11);

    hw_mult_16_0_mult_2_5: MULT2
        port map (A0=>rega_a_10, A1=>rega_a_11, A2=>rega_a_11, 
            A3=>rega_a_12, B0=>regb_b_3, B1=>regb_b_2, B2=>regb_b_3, 
            B3=>regb_b_2, CI=>mco_11, P0=>hw_mult_16_0_pp_1_13, 
            P1=>hw_mult_16_0_pp_1_14, CO=>mco_12);

    hw_mult_16_0_mult_2_6: MULT2
        port map (A0=>rega_a_12, A1=>rega_a_13, A2=>rega_a_13, 
            A3=>rega_a_14, B0=>regb_b_3, B1=>regb_b_2, B2=>regb_b_3, 
            B3=>regb_b_2, CI=>mco_12, P0=>hw_mult_16_0_pp_1_15, 
            P1=>hw_mult_16_0_pp_1_16, CO=>mco_13);

    hw_mult_16_0_mult_2_7: MULT2
        port map (A0=>rega_a_14, A1=>hw_mult_16_0_mult_2_7_n2, 
            A2=>hw_mult_16_0_mult_2_7_n1, A3=>scuba_vlo, B0=>regb_b_3, 
            B1=>scuba_vhi, B2=>scuba_vhi, B3=>regb_b_2, CI=>mco_13, 
            P0=>hw_mult_16_0_pp_1_17, P1=>hw_mult_16_0_pp_1_18, 
            CO=>mfco_1);

    hw_mult_16_0_mult_4_0: MULT2
        port map (A0=>rega_a_0, A1=>rega_a_1, A2=>rega_a_1, A3=>rega_a_2, 
            B0=>regb_b_5, B1=>regb_b_4, B2=>regb_b_5, B3=>regb_b_4, 
            CI=>hw_mult_16_0_cin_lr_4, P0=>hw_mult_16_0_pp_2_5, 
            P1=>hw_mult_16_0_pp_2_6, CO=>mco_14);

    hw_mult_16_0_mult_4_1: MULT2
        port map (A0=>rega_a_2, A1=>rega_a_3, A2=>rega_a_3, A3=>rega_a_4, 
            B0=>regb_b_5, B1=>regb_b_4, B2=>regb_b_5, B3=>regb_b_4, 
            CI=>mco_14, P0=>hw_mult_16_0_pp_2_7, P1=>hw_mult_16_0_pp_2_8, 
            CO=>mco_15);

    hw_mult_16_0_mult_4_2: MULT2
        port map (A0=>rega_a_4, A1=>rega_a_5, A2=>rega_a_5, A3=>rega_a_6, 
            B0=>regb_b_5, B1=>regb_b_4, B2=>regb_b_5, B3=>regb_b_4, 
            CI=>mco_15, P0=>hw_mult_16_0_pp_2_9, 
            P1=>hw_mult_16_0_pp_2_10, CO=>mco_16);

    hw_mult_16_0_mult_4_3: MULT2
        port map (A0=>rega_a_6, A1=>rega_a_7, A2=>rega_a_7, A3=>rega_a_8, 
            B0=>regb_b_5, B1=>regb_b_4, B2=>regb_b_5, B3=>regb_b_4, 
            CI=>mco_16, P0=>hw_mult_16_0_pp_2_11, 
            P1=>hw_mult_16_0_pp_2_12, CO=>mco_17);

    hw_mult_16_0_mult_4_4: MULT2
        port map (A0=>rega_a_8, A1=>rega_a_9, A2=>rega_a_9, 
            A3=>rega_a_10, B0=>regb_b_5, B1=>regb_b_4, B2=>regb_b_5, 
            B3=>regb_b_4, CI=>mco_17, P0=>hw_mult_16_0_pp_2_13, 
            P1=>hw_mult_16_0_pp_2_14, CO=>mco_18);

    hw_mult_16_0_mult_4_5: MULT2
        port map (A0=>rega_a_10, A1=>rega_a_11, A2=>rega_a_11, 
            A3=>rega_a_12, B0=>regb_b_5, B1=>regb_b_4, B2=>regb_b_5, 
            B3=>regb_b_4, CI=>mco_18, P0=>hw_mult_16_0_pp_2_15, 
            P1=>hw_mult_16_0_pp_2_16, CO=>mco_19);

    hw_mult_16_0_mult_4_6: MULT2
        port map (A0=>rega_a_12, A1=>rega_a_13, A2=>rega_a_13, 
            A3=>rega_a_14, B0=>regb_b_5, B1=>regb_b_4, B2=>regb_b_5, 
            B3=>regb_b_4, CI=>mco_19, P0=>hw_mult_16_0_pp_2_17, 
            P1=>hw_mult_16_0_pp_2_18, CO=>mco_20);

    hw_mult_16_0_mult_4_7: MULT2
        port map (A0=>rega_a_14, A1=>hw_mult_16_0_mult_4_7_n2, 
            A2=>hw_mult_16_0_mult_4_7_n1, A3=>scuba_vlo, B0=>regb_b_5, 
            B1=>scuba_vhi, B2=>scuba_vhi, B3=>regb_b_4, CI=>mco_20, 
            P0=>hw_mult_16_0_pp_2_19, P1=>hw_mult_16_0_pp_2_20, 
            CO=>mfco_2);

    hw_mult_16_0_mult_6_0: MULT2
        port map (A0=>rega_a_0, A1=>rega_a_1, A2=>rega_a_1, A3=>rega_a_2, 
            B0=>regb_b_7, B1=>regb_b_6, B2=>regb_b_7, B3=>regb_b_6, 
            CI=>hw_mult_16_0_cin_lr_6, P0=>hw_mult_16_0_pp_3_7, 
            P1=>hw_mult_16_0_pp_3_8, CO=>mco_21);

    hw_mult_16_0_mult_6_1: MULT2
        port map (A0=>rega_a_2, A1=>rega_a_3, A2=>rega_a_3, A3=>rega_a_4, 
            B0=>regb_b_7, B1=>regb_b_6, B2=>regb_b_7, B3=>regb_b_6, 
            CI=>mco_21, P0=>hw_mult_16_0_pp_3_9, 
            P1=>hw_mult_16_0_pp_3_10, CO=>mco_22);

    hw_mult_16_0_mult_6_2: MULT2
        port map (A0=>rega_a_4, A1=>rega_a_5, A2=>rega_a_5, A3=>rega_a_6, 
            B0=>regb_b_7, B1=>regb_b_6, B2=>regb_b_7, B3=>regb_b_6, 
            CI=>mco_22, P0=>hw_mult_16_0_pp_3_11, 
            P1=>hw_mult_16_0_pp_3_12, CO=>mco_23);

    hw_mult_16_0_mult_6_3: MULT2
        port map (A0=>rega_a_6, A1=>rega_a_7, A2=>rega_a_7, A3=>rega_a_8, 
            B0=>regb_b_7, B1=>regb_b_6, B2=>regb_b_7, B3=>regb_b_6, 
            CI=>mco_23, P0=>hw_mult_16_0_pp_3_13, 
            P1=>hw_mult_16_0_pp_3_14, CO=>mco_24);

    hw_mult_16_0_mult_6_4: MULT2
        port map (A0=>rega_a_8, A1=>rega_a_9, A2=>rega_a_9, 
            A3=>rega_a_10, B0=>regb_b_7, B1=>regb_b_6, B2=>regb_b_7, 
            B3=>regb_b_6, CI=>mco_24, P0=>hw_mult_16_0_pp_3_15, 
            P1=>hw_mult_16_0_pp_3_16, CO=>mco_25);

    hw_mult_16_0_mult_6_5: MULT2
        port map (A0=>rega_a_10, A1=>rega_a_11, A2=>rega_a_11, 
            A3=>rega_a_12, B0=>regb_b_7, B1=>regb_b_6, B2=>regb_b_7, 
            B3=>regb_b_6, CI=>mco_25, P0=>hw_mult_16_0_pp_3_17, 
            P1=>hw_mult_16_0_pp_3_18, CO=>mco_26);

    hw_mult_16_0_mult_6_6: MULT2
        port map (A0=>rega_a_12, A1=>rega_a_13, A2=>rega_a_13, 
            A3=>rega_a_14, B0=>regb_b_7, B1=>regb_b_6, B2=>regb_b_7, 
            B3=>regb_b_6, CI=>mco_26, P0=>hw_mult_16_0_pp_3_19, 
            P1=>hw_mult_16_0_pp_3_20, CO=>mco_27);

    hw_mult_16_0_mult_6_7: MULT2
        port map (A0=>rega_a_14, A1=>hw_mult_16_0_mult_6_7_n2, 
            A2=>hw_mult_16_0_mult_6_7_n1, A3=>scuba_vlo, B0=>regb_b_7, 
            B1=>scuba_vhi, B2=>scuba_vhi, B3=>regb_b_6, CI=>mco_27, 
            P0=>hw_mult_16_0_pp_3_21, P1=>hw_mult_16_0_pp_3_22, 
            CO=>mfco_3);

    hw_mult_16_0_mult_8_0: MULT2
        port map (A0=>rega_a_0, A1=>rega_a_1, A2=>rega_a_1, A3=>rega_a_2, 
            B0=>regb_b_9, B1=>regb_b_8, B2=>regb_b_9, B3=>regb_b_8, 
            CI=>hw_mult_16_0_cin_lr_8, P0=>hw_mult_16_0_pp_4_9, 
            P1=>hw_mult_16_0_pp_4_10, CO=>mco_28);

    hw_mult_16_0_mult_8_1: MULT2
        port map (A0=>rega_a_2, A1=>rega_a_3, A2=>rega_a_3, A3=>rega_a_4, 
            B0=>regb_b_9, B1=>regb_b_8, B2=>regb_b_9, B3=>regb_b_8, 
            CI=>mco_28, P0=>hw_mult_16_0_pp_4_11, 
            P1=>hw_mult_16_0_pp_4_12, CO=>mco_29);

    hw_mult_16_0_mult_8_2: MULT2
        port map (A0=>rega_a_4, A1=>rega_a_5, A2=>rega_a_5, A3=>rega_a_6, 
            B0=>regb_b_9, B1=>regb_b_8, B2=>regb_b_9, B3=>regb_b_8, 
            CI=>mco_29, P0=>hw_mult_16_0_pp_4_13, 
            P1=>hw_mult_16_0_pp_4_14, CO=>mco_30);

    hw_mult_16_0_mult_8_3: MULT2
        port map (A0=>rega_a_6, A1=>rega_a_7, A2=>rega_a_7, A3=>rega_a_8, 
            B0=>regb_b_9, B1=>regb_b_8, B2=>regb_b_9, B3=>regb_b_8, 
            CI=>mco_30, P0=>hw_mult_16_0_pp_4_15, 
            P1=>hw_mult_16_0_pp_4_16, CO=>mco_31);

    hw_mult_16_0_mult_8_4: MULT2
        port map (A0=>rega_a_8, A1=>rega_a_9, A2=>rega_a_9, 
            A3=>rega_a_10, B0=>regb_b_9, B1=>regb_b_8, B2=>regb_b_9, 
            B3=>regb_b_8, CI=>mco_31, P0=>hw_mult_16_0_pp_4_17, 
            P1=>hw_mult_16_0_pp_4_18, CO=>mco_32);

    hw_mult_16_0_mult_8_5: MULT2
        port map (A0=>rega_a_10, A1=>rega_a_11, A2=>rega_a_11, 
            A3=>rega_a_12, B0=>regb_b_9, B1=>regb_b_8, B2=>regb_b_9, 
            B3=>regb_b_8, CI=>mco_32, P0=>hw_mult_16_0_pp_4_19, 
            P1=>hw_mult_16_0_pp_4_20, CO=>mco_33);

    hw_mult_16_0_mult_8_6: MULT2
        port map (A0=>rega_a_12, A1=>rega_a_13, A2=>rega_a_13, 
            A3=>rega_a_14, B0=>regb_b_9, B1=>regb_b_8, B2=>regb_b_9, 
            B3=>regb_b_8, CI=>mco_33, P0=>hw_mult_16_0_pp_4_21, 
            P1=>hw_mult_16_0_pp_4_22, CO=>mco_34);

    hw_mult_16_0_mult_8_7: MULT2
        port map (A0=>rega_a_14, A1=>hw_mult_16_0_mult_8_7_n2, 
            A2=>hw_mult_16_0_mult_8_7_n1, A3=>scuba_vlo, B0=>regb_b_9, 
            B1=>scuba_vhi, B2=>scuba_vhi, B3=>regb_b_8, CI=>mco_34, 
            P0=>hw_mult_16_0_pp_4_23, P1=>hw_mult_16_0_pp_4_24, 
            CO=>mfco_4);

    hw_mult_16_0_mult_10_0: MULT2
        port map (A0=>rega_a_0, A1=>rega_a_1, A2=>rega_a_1, A3=>rega_a_2, 
            B0=>regb_b_11, B1=>regb_b_10, B2=>regb_b_11, B3=>regb_b_10, 
            CI=>hw_mult_16_0_cin_lr_10, P0=>hw_mult_16_0_pp_5_11, 
            P1=>hw_mult_16_0_pp_5_12, CO=>mco_35);

    hw_mult_16_0_mult_10_1: MULT2
        port map (A0=>rega_a_2, A1=>rega_a_3, A2=>rega_a_3, A3=>rega_a_4, 
            B0=>regb_b_11, B1=>regb_b_10, B2=>regb_b_11, B3=>regb_b_10, 
            CI=>mco_35, P0=>hw_mult_16_0_pp_5_13, 
            P1=>hw_mult_16_0_pp_5_14, CO=>mco_36);

    hw_mult_16_0_mult_10_2: MULT2
        port map (A0=>rega_a_4, A1=>rega_a_5, A2=>rega_a_5, A3=>rega_a_6, 
            B0=>regb_b_11, B1=>regb_b_10, B2=>regb_b_11, B3=>regb_b_10, 
            CI=>mco_36, P0=>hw_mult_16_0_pp_5_15, 
            P1=>hw_mult_16_0_pp_5_16, CO=>mco_37);

    hw_mult_16_0_mult_10_3: MULT2
        port map (A0=>rega_a_6, A1=>rega_a_7, A2=>rega_a_7, A3=>rega_a_8, 
            B0=>regb_b_11, B1=>regb_b_10, B2=>regb_b_11, B3=>regb_b_10, 
            CI=>mco_37, P0=>hw_mult_16_0_pp_5_17, 
            P1=>hw_mult_16_0_pp_5_18, CO=>mco_38);

    hw_mult_16_0_mult_10_4: MULT2
        port map (A0=>rega_a_8, A1=>rega_a_9, A2=>rega_a_9, 
            A3=>rega_a_10, B0=>regb_b_11, B1=>regb_b_10, B2=>regb_b_11, 
            B3=>regb_b_10, CI=>mco_38, P0=>hw_mult_16_0_pp_5_19, 
            P1=>hw_mult_16_0_pp_5_20, CO=>mco_39);

    hw_mult_16_0_mult_10_5: MULT2
        port map (A0=>rega_a_10, A1=>rega_a_11, A2=>rega_a_11, 
            A3=>rega_a_12, B0=>regb_b_11, B1=>regb_b_10, B2=>regb_b_11, 
            B3=>regb_b_10, CI=>mco_39, P0=>hw_mult_16_0_pp_5_21, 
            P1=>hw_mult_16_0_pp_5_22, CO=>mco_40);

    hw_mult_16_0_mult_10_6: MULT2
        port map (A0=>rega_a_12, A1=>rega_a_13, A2=>rega_a_13, 
            A3=>rega_a_14, B0=>regb_b_11, B1=>regb_b_10, B2=>regb_b_11, 
            B3=>regb_b_10, CI=>mco_40, P0=>hw_mult_16_0_pp_5_23, 
            P1=>hw_mult_16_0_pp_5_24, CO=>mco_41);

    hw_mult_16_0_mult_10_7: MULT2
        port map (A0=>rega_a_14, A1=>hw_mult_16_0_mult_10_7_n2, 
            A2=>hw_mult_16_0_mult_10_7_n1, A3=>scuba_vlo, B0=>regb_b_11, 
            B1=>scuba_vhi, B2=>scuba_vhi, B3=>regb_b_10, CI=>mco_41, 
            P0=>hw_mult_16_0_pp_5_25, P1=>hw_mult_16_0_pp_5_26, 
            CO=>mfco_5);

    hw_mult_16_0_mult_12_0: MULT2
        port map (A0=>rega_a_0, A1=>rega_a_1, A2=>rega_a_1, A3=>rega_a_2, 
            B0=>regb_b_13, B1=>regb_b_12, B2=>regb_b_13, B3=>regb_b_12, 
            CI=>hw_mult_16_0_cin_lr_12, P0=>hw_mult_16_0_pp_6_13, 
            P1=>hw_mult_16_0_pp_6_14, CO=>mco_42);

    hw_mult_16_0_mult_12_1: MULT2
        port map (A0=>rega_a_2, A1=>rega_a_3, A2=>rega_a_3, A3=>rega_a_4, 
            B0=>regb_b_13, B1=>regb_b_12, B2=>regb_b_13, B3=>regb_b_12, 
            CI=>mco_42, P0=>hw_mult_16_0_pp_6_15, 
            P1=>hw_mult_16_0_pp_6_16, CO=>mco_43);

    hw_mult_16_0_mult_12_2: MULT2
        port map (A0=>rega_a_4, A1=>rega_a_5, A2=>rega_a_5, A3=>rega_a_6, 
            B0=>regb_b_13, B1=>regb_b_12, B2=>regb_b_13, B3=>regb_b_12, 
            CI=>mco_43, P0=>hw_mult_16_0_pp_6_17, 
            P1=>hw_mult_16_0_pp_6_18, CO=>mco_44);

    hw_mult_16_0_mult_12_3: MULT2
        port map (A0=>rega_a_6, A1=>rega_a_7, A2=>rega_a_7, A3=>rega_a_8, 
            B0=>regb_b_13, B1=>regb_b_12, B2=>regb_b_13, B3=>regb_b_12, 
            CI=>mco_44, P0=>hw_mult_16_0_pp_6_19, 
            P1=>hw_mult_16_0_pp_6_20, CO=>mco_45);

    hw_mult_16_0_mult_12_4: MULT2
        port map (A0=>rega_a_8, A1=>rega_a_9, A2=>rega_a_9, 
            A3=>rega_a_10, B0=>regb_b_13, B1=>regb_b_12, B2=>regb_b_13, 
            B3=>regb_b_12, CI=>mco_45, P0=>hw_mult_16_0_pp_6_21, 
            P1=>hw_mult_16_0_pp_6_22, CO=>mco_46);

    hw_mult_16_0_mult_12_5: MULT2
        port map (A0=>rega_a_10, A1=>rega_a_11, A2=>rega_a_11, 
            A3=>rega_a_12, B0=>regb_b_13, B1=>regb_b_12, B2=>regb_b_13, 
            B3=>regb_b_12, CI=>mco_46, P0=>hw_mult_16_0_pp_6_23, 
            P1=>hw_mult_16_0_pp_6_24, CO=>mco_47);

    hw_mult_16_0_mult_12_6: MULT2
        port map (A0=>rega_a_12, A1=>rega_a_13, A2=>rega_a_13, 
            A3=>rega_a_14, B0=>regb_b_13, B1=>regb_b_12, B2=>regb_b_13, 
            B3=>regb_b_12, CI=>mco_47, P0=>hw_mult_16_0_pp_6_25, 
            P1=>hw_mult_16_0_pp_6_26, CO=>mco_48);

    hw_mult_16_0_mult_12_7: MULT2
        port map (A0=>rega_a_14, A1=>hw_mult_16_0_mult_12_7_n2, 
            A2=>hw_mult_16_0_mult_12_7_n1, A3=>scuba_vlo, B0=>regb_b_13, 
            B1=>scuba_vhi, B2=>scuba_vhi, B3=>regb_b_12, CI=>mco_48, 
            P0=>hw_mult_16_0_pp_6_27, P1=>hw_mult_16_0_pp_6_28, 
            CO=>mfco_6);

    hw_mult_16_0_mult_14_0: MULT2
        port map (A0=>hw_mult_16_0_mult_14_0_n0, A1=>rega_a_1, 
            A2=>hw_mult_16_0_mult_14_0_n1, A3=>rega_a_2, B0=>scuba_vhi, 
            B1=>regb_b_14, B2=>scuba_vhi, B3=>regb_b_14, 
            CI=>hw_mult_16_0_cin_lr_14, P0=>hw_mult_16_0_pp_7_15, 
            P1=>hw_mult_16_0_pp_7_16, CO=>mco_49);

    hw_mult_16_0_mult_14_1: MULT2
        port map (A0=>hw_mult_16_0_mult_14_1_n0, A1=>rega_a_3, 
            A2=>hw_mult_16_0_mult_14_1_n1, A3=>rega_a_4, B0=>scuba_vhi, 
            B1=>regb_b_14, B2=>scuba_vhi, B3=>regb_b_14, CI=>mco_49, 
            P0=>hw_mult_16_0_pp_7_17, P1=>hw_mult_16_0_pp_7_18, 
            CO=>mco_50);

    hw_mult_16_0_mult_14_2: MULT2
        port map (A0=>hw_mult_16_0_mult_14_2_n0, A1=>rega_a_5, 
            A2=>hw_mult_16_0_mult_14_2_n1, A3=>rega_a_6, B0=>scuba_vhi, 
            B1=>regb_b_14, B2=>scuba_vhi, B3=>regb_b_14, CI=>mco_50, 
            P0=>hw_mult_16_0_pp_7_19, P1=>hw_mult_16_0_pp_7_20, 
            CO=>mco_51);

    hw_mult_16_0_mult_14_3: MULT2
        port map (A0=>hw_mult_16_0_mult_14_3_n0, A1=>rega_a_7, 
            A2=>hw_mult_16_0_mult_14_3_n1, A3=>rega_a_8, B0=>scuba_vhi, 
            B1=>regb_b_14, B2=>scuba_vhi, B3=>regb_b_14, CI=>mco_51, 
            P0=>hw_mult_16_0_pp_7_21, P1=>hw_mult_16_0_pp_7_22, 
            CO=>mco_52);

    hw_mult_16_0_mult_14_4: MULT2
        port map (A0=>hw_mult_16_0_mult_14_4_n0, A1=>rega_a_9, 
            A2=>hw_mult_16_0_mult_14_4_n1, A3=>rega_a_10, B0=>scuba_vhi, 
            B1=>regb_b_14, B2=>scuba_vhi, B3=>regb_b_14, CI=>mco_52, 
            P0=>hw_mult_16_0_pp_7_23, P1=>hw_mult_16_0_pp_7_24, 
            CO=>mco_53);

    hw_mult_16_0_mult_14_5: MULT2
        port map (A0=>hw_mult_16_0_mult_14_5_n0, A1=>rega_a_11, 
            A2=>hw_mult_16_0_mult_14_5_n1, A3=>rega_a_12, B0=>scuba_vhi, 
            B1=>regb_b_14, B2=>scuba_vhi, B3=>regb_b_14, CI=>mco_53, 
            P0=>hw_mult_16_0_pp_7_25, P1=>hw_mult_16_0_pp_7_26, 
            CO=>mco_54);

    hw_mult_16_0_mult_14_6: MULT2
        port map (A0=>hw_mult_16_0_mult_14_6_n0, A1=>rega_a_13, 
            A2=>hw_mult_16_0_mult_14_6_n1, A3=>rega_a_14, B0=>scuba_vhi, 
            B1=>regb_b_14, B2=>scuba_vhi, B3=>regb_b_14, CI=>mco_54, 
            P0=>hw_mult_16_0_pp_7_27, P1=>hw_mult_16_0_pp_7_28, 
            CO=>mco_55);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    hw_mult_16_0_mult_14_7: MULT2
        port map (A0=>hw_mult_16_0_mult_14_7_n0, 
            A1=>hw_mult_16_0_mult_14_7_n2, A2=>rega_a_15, A3=>scuba_vlo, 
            B0=>scuba_vhi, B1=>scuba_vhi, B2=>regb_b_15, B3=>regb_b_14, 
            CI=>mco_55, P0=>hw_mult_16_0_pp_7_29, 
            P1=>hw_mult_16_0_pp_7_30, CO=>mfco_7);

    rego_o_0 <= hw_mult_16_0_pp_0_0;
    rego_o_1 <= hw_mult_16_0_pp_0_1;
    rego_o_2 <= s_hw_mult_16_0_0_2;
    rego_o_3 <= s_hw_mult_16_0_0_3;
    rego_o_4 <= s_hw_mult_16_0_4_4;
    rego_o_5 <= s_hw_mult_16_0_4_5;
    rego_o_6 <= s_hw_mult_16_0_4_6;
    rego_o_7 <= s_hw_mult_16_0_4_7;
end Structure;

-- synopsys translate_off
library MACHXO3L;
configuration Structure_CON of hw_mult_16 is
    for Structure
        for all:AND2 use entity MACHXO3L.AND2(V); end for;
        for all:FADD2B use entity MACHXO3L.FADD2B(V); end for;
        for all:FD1P3DX use entity MACHXO3L.FD1P3DX(V); end for;
        for all:ND2 use entity MACHXO3L.ND2(V); end for;
        for all:VHI use entity MACHXO3L.VHI(V); end for;
        for all:VLO use entity MACHXO3L.VLO(V); end for;
        for all:MULT2 use entity MACHXO3L.MULT2(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
