-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.2.446.3
-- Module  Version: 7.5
-- Sat Apr 25 14:19:28 2020

-- parameterized module component declaration
component fastram_ebr
    port (Clock: in  std_logic; ClockEn: in  std_logic; 
        Reset: in  std_logic; ByteEn: in  std_logic_vector(1 downto 0); 
        WE: in  std_logic; Address: in  std_logic_vector(11 downto 0); 
        Data: in  std_logic_vector(15 downto 0); 
        Q: out  std_logic_vector(15 downto 0));
end component;

-- parameterized module component instance
__ : fastram_ebr
    port map (Clock=>__, ClockEn=>__, Reset=>__, ByteEn(1 downto 0)=>__, 
        WE=>__, Address(11 downto 0)=>__, Data(15 downto 0)=>__, Q(15 downto 0)=>__);
