-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.2.446.3
-- Module  Version: 4.9
-- Sat Apr 25 12:46:37 2020

-- parameterized module component declaration
component hw_mult_16
    port (Clock: in  std_logic; ClkEn: in  std_logic; 
        Aclr: in  std_logic; DataA: in  std_logic_vector(15 downto 0); 
        DataB: in  std_logic_vector(15 downto 0); 
        Result: out  std_logic_vector(31 downto 0));
end component;

-- parameterized module component instance
__ : hw_mult_16
    port map (Clock=>__, ClkEn=>__, Aclr=>__, DataA(15 downto 0)=>__, 
        DataB(15 downto 0)=>__, Result(31 downto 0)=>__);
